# 넘파이의 데이터 구조

넘파이의 자료형은 ndarray. 효율적인 배열 연산을 위해 개발되었고, 리스트와 ndarray는 유연성과 효율성을 기준으로 비교할 수 있다.

List는 유연성 면에서 서로 다른 데이터 타입을 담을 수 있지만 ndarray는 서로 다른 데이터 타입의 요소를 담을 수 없다.  
ndarray는 효율성 면에서 모든 요소 정보를 한 번에 저장할 수 있고, C로 구현된 내부 반복문을 사용하기 때문에 속도가 매우 빠르다. 그러나 List는 각 요소 정보를 따로 저장하고, 반복문 사용이 필수적이다.  

## 배열 만들기

### 리스트에서 배열 만들기

In [2]:
import numpy as np

a = np.array([1, 4, 2, 5, 3])
b = np.array([3.14, 4, 2, 3])
c = np.array([1, 2, 3, 4], dtype = float)

print(a, b, c)

[1 4 2 5 3] [3.14 4.   2.   3.  ] [1. 2. 3. 4.]


In [3]:
# 떼어서 출력하면 다른점이 보인다.
a

array([1, 4, 2, 5, 3])

In [4]:
b

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
c

array([1., 2., 3., 4.])

a는 int, b는 float인 것이 보인다. 또한 c는 float으로 지정해주었기 때문에 float으로 보인다.

### numpy로 배열 만들기

> `np.zeros(shape)`  
shape(튜플) 모양을 갖는 영벡터/영행렬 생성.  
`np.zeros((10,2))`: (10,2) 크기의 영행렬 생성.  

> `np.ones(shape)`  
shape(튜플) 모양을 갖는 1로 채운 배열 생성.  
`np.zeros((10,2))`: 원소가 1인 (10,2) 크기의 행렬 생성.  

> `np.full((n, m), i)`  
$i$로 채운 $n\times m$ 크기의 배열 생성.  

> `np.arange(start, stop, step)`  
start부터 stop까지 step만큼 건너뛰는 1차원 ndarray를 반환한다. start와 step은 생략 가능하다.  

> `np.linspace(start, stop, num)`  
start부터 stop 까지 num 개수의 요소를 가지는 등간격의 1차원 배열을 반환한다.   

> `np.eye(i)`  
크기 $i$의 단위 행렬 만들기  

#### np.random 에 있는 메서드

> `np.random.random((n, m))`  
$n\times m$ 크기의 난수 배열 생성

> `np.random.noraml(i, j, (n, m))`  
평균이 $i$이고 분산이 $j$인 정규분포를 이루는 $n\times m$ 크기의 난수 배열 생성  

> `np.random.randint(i, j, (n, m))`. 
$i$와 $j$ 구간 사이의 임의의 정수로 $n\times m$ 크기의 난수 배열 생성  


In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [12]:
np.linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])