In [1]:
import numpy as np

# 넘파이의 연산과 함수
231027

(동빈나 유튜브)[https://www.youtube.com/watch?v=k4bTgociqZ8]

## 1. 스칼라 연산

In [2]:
array = np.random.randint(1, 10, size = 4).reshape(2, 2)
print(array)

[[4 2]
 [3 2]]


In [3]:
result_array = array*10
print(result_array)

[[40 20]
 [30 20]]


## 2. 서로 다른 형태의 Numpy 연산
- Numpy는 서로 다른 형태의 배열을 연산할 때는 행 우선으로 수행됩니다.

In [4]:
array1 = np.arange(4).reshape(2, 2) # 2by2
array2 = np.arange(2) # 1by2
print(array1)
print(array2)

[[0 1]
 [2 3]]
[0 1]


In [5]:
array1 + array2

array([[0, 2],
       [2, 4]])

- 브로드캐스팅 적용 예시2

In [6]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
# 두 어레이 합치기 - 세로축으로
array3 = np.concatenate([array1, array2], axis = 0)

print(array3)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [7]:
array4 = np.arange(0, 4).reshape(4, 1) # 4X 1
print(array4)

[[0]
 [1]
 [2]
 [3]]


In [8]:
print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


## 3. Numpy의 마스킹 연산

In [9]:
array1 = np.arange(16).reshape(4, 4)
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
# 10보다 큰가?
array2 = array1 > 10
print(array2)

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]


In [11]:
# 마스킹 연산의 활용
# TF마스킹된 배열을 넣게되면
# 그 조건을 만족하는 데이터만 어떠한 작업을 하도록 명시할 수 있다.

# 조건에 맞는 원소들만 값이 바뀌도록 함

array1[array2] = 100
print(array1)

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]
 [100 100 100 100]]


In [12]:
# 이 작업은 조건에 맞는 원소들의 배열이 아니라 그 원소들의 값만 바꾼다.

array1 = np.arange(16).reshape(4, 4)
array2 = array1 > 10

array1[array2] * 100  # 10초과의 값들이 100 씩 곱해짐

array([1100, 1200, 1300, 1400, 1500])

## 4. Numpy의 집계함수



In [13]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print(array)
print('최대값:', np.max(array))
print('최소값:', np.min(array))
print('합계:', np.sum(array))
print('평균값:', np.mean(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
최대값: 15
최소값: 0
합계: 120
평균값: 7.5


각각의 축에 대해서 값을 구하도록 수행할 수도 있다.

In [14]:
print(array)
print('최대값:', np.max(array, axis = 0))
print('최소값:', np.min(array, axis = 0))
print('합계:', np.sum(array, axis = 0))
print('평균값:', np.mean(array, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
최대값: [12 13 14 15]
최소값: [0 1 2 3]
합계: [24 28 32 36]
평균값: [6. 7. 8. 9.]


In [15]:
np.sum(array, axis = 0)[0]

24