<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Configuring-pandas" data-toc-modified-id="Configuring-pandas-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Configuring pandas</a></span></li><li><span><a href="#범주형-데이터" data-toc-modified-id="범주형-데이터-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>범주형 데이터</a></span></li><li><span><a href="#Creating-Categoricals" data-toc-modified-id="Creating-Categoricals-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Creating Categoricals</a></span><ul class="toc-item"><li><span><a href="#리스트로부터-만들기" data-toc-modified-id="리스트로부터-만들기-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>리스트로부터 만들기</a></span><ul class="toc-item"><li><span><a href="#.categorical-로-범주-확인하기" data-toc-modified-id=".categorical-로-범주-확인하기-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span><code>.categorical</code> 로 범주 확인하기</a></span></li><li><span><a href="#.codes-:-할당된-정수-code-확인" data-toc-modified-id=".codes-:-할당된-정수-code-확인-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span><code>.codes</code> : 할당된 정수 code 확인</a></span></li><li><span><a href="#코드-순서-정하기" data-toc-modified-id="코드-순서-정하기-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>코드 순서 정하기</a></span></li></ul></li><li><span><a href="#범주형-시리즈-만들기:-pd.Series(categoryarray,-dtype=&quot;category&quot;)" data-toc-modified-id="범주형-시리즈-만들기:-pd.Series(categoryarray,-dtype=&quot;category&quot;)-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>범주형 시리즈 만들기: <code>pd.Series(categoryarray, dtype="category")</code></a></span></li><li><span><a href="#범주형-시리즈-만들기-:-.astype('category')" data-toc-modified-id="범주형-시리즈-만들기-:-.astype('category')-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>범주형 시리즈 만들기 : <code>.astype('category')</code></a></span><ul class="toc-item"><li><span><a href="#.cat-Attribute-:-CategoricalAccessor-를-반환하는-속성" data-toc-modified-id=".cat-Attribute-:-CategoricalAccessor-를-반환하는-속성-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span><code>.cat</code> Attribute : CategoricalAccessor 를 반환하는 속성</a></span><ul class="toc-item"><li><span><a href="#.cat.categories" data-toc-modified-id=".cat.categories-3.3.1.1"><span class="toc-item-num">3.3.1.1&nbsp;&nbsp;</span><code>.cat.categories</code></a></span></li></ul></li></ul></li><li><span><a href="#pd.cut()-:-범주형-구간-만들기" data-toc-modified-id="pd.cut()-:-범주형-구간-만들기-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span><code>pd.cut()</code> : 범주형 구간 만들기</a></span></li><li><span><a href="#pd.Categorical(ordered-=-True)-파라미터" data-toc-modified-id="pd.Categorical(ordered-=-True)-파라미터-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span><code>pd.Categorical(ordered = True)</code> 파라미터</a></span></li><li><span><a href="#범주에-속하지-않는-값이-들어왔을-경우" data-toc-modified-id="범주에-속하지-않는-값이-들어왔을-경우-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>범주에 속하지 않는 값이 들어왔을 경우</a></span></li></ul></li><li><span><a href="#Renaming-Categories" data-toc-modified-id="Renaming-Categories-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Renaming Categories</a></span><ul class="toc-item"><li><span><a href="#.categories-attribute로-변경하기" data-toc-modified-id=".categories-attribute로-변경하기-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span><code>.categories</code> attribute로 변경하기</a></span></li><li><span><a href="#.rename_categories()-method로-변경하기" data-toc-modified-id=".rename_categories()-method로-변경하기-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span><code>.rename_categories()</code> method로 변경하기</a></span></li></ul></li><li><span><a href="#.add_categories()-:-Appending-new-categories" data-toc-modified-id=".add_categories()-:-Appending-new-categories-5"><span class="toc-item-num">5&nbsp;&nbsp;</span><code>.add_categories()</code> : Appending new categories</a></span></li><li><span><a href="#.remove_categories()-:-Removing-Categories" data-toc-modified-id=".remove_categories()-:-Removing-Categories-6"><span class="toc-item-num">6&nbsp;&nbsp;</span><code>.remove_categories()</code> : Removing Categories</a></span></li><li><span><a href="#.remove_unused_categories()-:-Removing-unused-categories" data-toc-modified-id=".remove_unused_categories()-:-Removing-unused-categories-7"><span class="toc-item-num">7&nbsp;&nbsp;</span><code>.remove_unused_categories()</code> : Removing unused categories</a></span></li><li><span><a href="#.set_categories()-:-Setting-categories" data-toc-modified-id=".set_categories()-:-Setting-categories-8"><span class="toc-item-num">8&nbsp;&nbsp;</span><code>.set_categories()</code> : Setting categories</a></span></li><li><span><a href="#기술-통계-정보-:-Describe()" data-toc-modified-id="기술-통계-정보-:-Describe()-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>기술 통계 정보 : <code>Describe()</code></a></span><ul class="toc-item"><li><span><a href="#Value-counts" data-toc-modified-id="Value-counts-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Value counts</a></span></li><li><span><a href="#Minimum,-maximum-and-mode" data-toc-modified-id="Minimum,-maximum-and-mode-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Minimum, maximum and mode</a></span></li></ul></li><li><span><a href="#Example:-Munging-school-grades" data-toc-modified-id="Example:-Munging-school-grades-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Example: Munging school grades</a></span></li><li><span><a href="#my-sample-:" data-toc-modified-id="my-sample-:-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>my sample :</a></span></li></ul></div>

# Configuring pandas

In [1]:
# import numpy and pandas
import numpy as np
import pandas as pd

# used for dates
import datetime
from datetime import datetime, date

# Set some pandas options controlling output format
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 60)

# bring in matplotlib for graphics
import matplotlib.pyplot as plt
%matplotlib inline

# version check
print(pd.__version__)
print(np.__version__)
import sys
print(sys.version)

1.4.1
1.22.4
3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]


# 범주형 데이터
범주형 변수(categorical variable)는 대개 제한되고 고정된 데이터셋을 표현하는 통계학에서의 변수 유형이다. 범주형 변수는 값을 무한히 표현할 수 있는 연속 변수(continuous variable)와 대비된다. 성별, 혈액형 등이 범주형 변수의 예다.  
pandas에서 범주형 변수는 `Categorical`이라는 pandas 객체를 사용해 표현한다. 이 객체는 각 범주를 나타내는 정수 코드의 그룹으로, 데이터를 효율적으로 표현하기 위해 설계됐다. 이로써 pandas는 범주 집합의 효율적인 표현뿐만 아니라 여러 범주형 변수를 정렬하거나 비교하는 능력을 갖추게 됐다. 

- `Categorical` 생성
- 범주 이름 변경
- 새 범주 추가
- 범주 삭제
- 미사용 범주 삭제
- 범주 설정
- 기술 통계
- 값의 수 세기
- 최댓값, 최솟값, 최빈값
- `Categorical`을 사용해 학생의 숫자 등급에 문자 등급을 할당하는 방법


# Creating Categoricals
---
`Categorical` 생성

pandas의 `Categorical`은 범주형 변수를 표현하기 위해 사용된다. 범주형 변수는 한정된 값의 집합으로 구성되며, 종종 값을 범주에 매핑하거나 각 범주에 있는 값의 개수를 추적할 때 사용된다. 

또 다른 목적은 연속적인 값들의 구획을 나눠 개별 레이블에 매핑시키기 위해서다. 예를 들면 숫자로 된 등급을 문자로 된 등급에 매핑시키는 일 등이다. 그런 매핑은 뒤쪽에서!

pandas의 `Categorical`을 만드는 방법은 다양하다. 

## 리스트로부터 만들기

In [2]:
# create a categorical directly from a list.  
lmh_values = ["low", "high", "medium", "medium", "high"]
lmh_cat = pd.Categorical(lmh_values)
lmh_cat

['low', 'high', 'medium', 'medium', 'high']
Categories (3, object): ['high', 'low', 'medium']

세 가지로 된 값을 가지고, 5개의 문자열 리스트로 이루어져있다.  
pandas는 `Categorical`이 생성될 때 리스트에서 유일한 값들을 판별하고 이를 범주로 사용한다.  

###  `.categorical` 로 범주 확인하기 
만들어진 범주는 `.categorical` 속성을 사용해 확인할 수 있다. 해당 카테고리들로 데이터가 이루어져있음을 알 수 있다. 

In [3]:
# examine the categories
lmh_cat.categories

Index(['high', 'low', 'medium'], dtype='object')

 `.get_values()` 로 값 가져오는 것은 버전의 문제로 더 이상 되지 않는다.  
 

In [ ]:
# retreive the values
lmh_cat.get_values()

### `.codes` : 할당된 정수 code 확인

 `Categorical`의 각 범주에는 정수 값이 할당되는데, 이를 코드(code)라고 한다. 

In [5]:
# .codes shows the integer mapping for each value of the categorical
lmh_cat.codes

array([1, 0, 2, 2, 0], dtype=int8)

### 코드 순서 정하기

이들 코드는 범주형 인덱스의 포지션을 효과적으로 나타낸다. (여기서는 low = 1, high = 0, medium = 2 인데, 알파벳 순서로 padnas가 문자열을 순차적으로 처리하면서 결정한 것으로 보인다.)  
이 순서는 생성할 당시의 `categories` 파라미터를 통해 범주를 지정함으로써 통제할 수 있다. 파라미터에 순서대로 리스트를 주어준다. 


In [6]:
# create from list but explicitly state the categories
lmh_cat = pd.Categorical(lmh_values,
                         categories=["low", "medium", "high"])
lmh_cat

['low', 'high', 'medium', 'medium', 'high']
Categories (3, object): ['low', 'medium', 'high']

In [7]:
# the codes are...
lmh_cat.codes

array([0, 2, 1, 1, 2], dtype=int8)

이제 low = 0, medium = 1, high = 2 가 됐다. 각 범주의 의미와 상통하는 순서로 값이 정렬(sorting)됐으므로 유용하게 됐다.  

`Categorical`의 정렬은 실제 값이 아닌 코드를 기준으로 수행되기 때문에 더 유용하게 됐다. 정렬해보자. 

In [8]:
# sorting is done using the codes underlying each value
lmh_cat.sort_values()

['low', 'medium', 'medium', 'high', 'high']
Categories (3, object): ['low', 'medium', 'high']

## 범주형 시리즈 만들기: `pd.Series(categoryarray, dtype="category")` 
##### Categorical : Series, dtype = category
범주형 변수는 dtype이 category인 하나의 시리즈로 표현될 수 있다.  
다음은 범주 배열을 받아서 dtype이 category인 series를 만드는 예시이다. 

In [9]:
# create a categorical using a Series and dtype
cat_series = pd.Series(lmh_values, dtype = 'category')
cat_series

0       low
1      high
2    medium
3    medium
4      high
dtype: category
Categories (3, object): ['high', 'low', 'medium']

## 범주형 시리즈 만들기 : `.astype('category')` 
범주형 Series를 만드는 또 다른 방법은 먼저 Series를 하나 만든 다음, `.astype('category')` 메서드를 사용해 범주형으로 바꿔주는 것이다.  

In [10]:
# create a categorical using .astype()
s = pd.Series(lmh_values)
as_cat_series = s.astype('category')
as_cat_series

0       low
1      high
2    medium
3    medium
4      high
dtype: category
Categories (3, object): ['high', 'low', 'medium']

### `.cat` Attribute : CategoricalAccessor 를 반환하는 속성

In [11]:
# a categorical has a .cat property that lets you access info
cat_series.cat

#### `.cat.categories`
CategoricalAccessor 는 범주형의 여러 정보에 접근할 수 있게 하는 객체이다. 예를 들어 다음과 같이 범주를 가져올 수 있다. 

In [12]:
# get the index for the categorical
cat_series.cat.categories

Index(['high', 'low', 'medium'], dtype='object')

## `pd.cut()` : 범주형 구간 만들기
`Categorical`을 반환해주는 여러 pandas 함수들이 있는데, `pd.cut()`은 특정 범위에 포함되는 객체의 구간(bins)을 만든다.  

다음은 0부터 100 사이에 있는 5개의 난수를 정수 10만큼의 크기를 갖는 10개의 범주형 구간으로 분류시킨 예이다. 

`pd.cut()`함수로 생성된 범주형 변수가 Group 칼럼이고, 각 인덱스 레이블의 값은 특정 범주와 연결된다. 

In [13]:
# create a DataFrame of 100 values : 0~100사이의 랜덤 값을 갖도록 데이터를 만듬
np.random.seed(123456)
values = np.random.randint(0, 100, 5)
bins = pd.DataFrame({"Values": values})
bins

   Values
0      65
1      49
2      56
3      43
4      43

In [14]:
# cut the values into : cut를 이용해, range로 0부터 100의 범위를 10개로 나눈 것을 그룹에 들어가도록 함
bins['Group'] = pd.cut(values, range(0, 101, 10))
bins

   Values     Group
0      65  (60, 70]
1      49  (40, 50]
2      56  (50, 60]
3      43  (40, 50]
4      43  (40, 50]

Group 칼럼의 dtype을 찍어보면 category 로 나온다. 

In [15]:
# examine the categorical that was created
bins.Group

0    (60, 70]
1    (40, 50]
2    (50, 60]
3    (40, 50]
4    (40, 50]
Name: Group, dtype: category
Categories (10, interval[int64, right]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

## `pd.Categorical(ordered = True)` 파라미터
`ordered = True`를 사용하면 명시적으로 범주의 순서를 정렬할 수 있다. 이는 범주의 순서가 중요한 의미를 가진다는 점을 나타내며, 범주형 변수의 여러 시리즈 사이의 값 비교를 가능하게 해준다.  

다음은 세 종류의 금속을 나타내는 순서를 갖는 `Categorical`을 생성하는 예시인데, 일종의 **엄격한 순서를 갖도록** 하게 된다.  
이와 같은 순서는 `Categorical`끼리 정렬하거나 비교하는 용도로 사용될 수 있다. 

In [16]:
# create an ordered categorical of precious metals
# order is important for determining relative value
metal_values = ["bronze", "gold", "silver", "bronze"]
metal_categories = ["bronze", "silver", "gold"]
metals = pd.Categorical(metal_values,
                        categories=metal_categories,
                        ordered = True)
metals

['bronze', 'gold', 'silver', 'bronze']
Categories (3, object): ['bronze' < 'silver' < 'gold']

시험하기 위해 원래 값을 거꾸로 나열한 `Categorical`을 만들어본다.  

    `Categorical`이 `.get_values()`를 사용할 수 없다는 오류 때문에 따로 만들었다. 

In [ ]:
"""
원본 코드

# reverse the metals
metals_reversed_values = pd.Categorical(
                                        metals.get_values()[::-1],
                                        categories = metals.categories, 
                                        ordered=True)
metals_reversed_values
"""

In [17]:
# reverse the metals
metals_values2 = ["bronze", "silver", "gold", "bronze"]
metals_reversed_values = pd.Categorical(metals_values2,
                                        categories = metals.categories, # 값의 우열은 위에 만들었던 것과 같음
                                        ordered=True)
metals_reversed_values

['bronze', 'silver', 'gold', 'bronze']
Categories (3, object): ['bronze' < 'silver' < 'gold']

이제 두 범주형 변수를 서로 비교할 수 있다. 동일한 인덱스 레이블에 해당하는 금속의 가치를 각각 비교하는 예시이다. 

pandas는 각 값이 갖는 코드를 일치시킴으로써, 이와 같은 **비교를 수행할 수 있다.**  
`.codes`를 통해 각 값이 어느 카테고리에 속하는지 볼 수 있다. 여기에 논리 연산자가 적용돼서 결과를 볼 수 있는 것이다. 

In [18]:
# compare the two categoricals 
metals <= metals_reversed_values

array([ True, False,  True,  True])

In [19]:
# codes are the integer value assocaited with each item
metals.codes

array([0, 2, 1, 0], dtype=int8)

In [20]:
# and for metals2
metals_reversed_values.codes

array([0, 1, 2, 0], dtype=int8)

## 범주에 속하지 않는 값이 들어왔을 경우
어떤 범주에도 속하지 않는 값을 지정할 경우, pandas는 그 값을 `NaN`으로 대체한다.  

어디에도 속하지 않는 'copper'를 지정한 상황을 보자.

In [21]:
# creating a categorical with a non existent category
pd.Categorical(["bronze", "copper"],
               categories = metal_categories)

['bronze', NaN]
Categories (3, object): ['bronze', 'silver', 'gold']

In [22]:
# 임의로 리스트를 만들어 지정해보아도 똑같다. 백금과 팔라듐, 티타늄, 로듐, 수은을 넣어버렸다.
metal_values3 = ['bronze', 'copper', 'platinum', 'gold', 'silver', 'palladium', 'titanium', 'rhodium', 'hydrargyrum']
pd.Categorical(metal_values3,
               categories = metal_categories)

['bronze', NaN, NaN, 'gold', 'silver', NaN, NaN, NaN, NaN]
Categories (3, object): ['bronze', 'silver', 'gold']

In [23]:
# 예시로 LoL의 계급체계를 만들어봅시다. 
# 언랭은 카테고리로 넣지 않습니다. 실력을 알 수 없기 때문이죠.
lol_ranks = ['iron', 'bronze', 'silver', 'gold', 'platinum', 'diamond', 'master', 'grandmaster', 'challenger']
user_ranks01 = ['silver', 'silver', 'silver', 'gold', 'bronze', 'bronze', 'diamond', 'silver', 'bronze', 'unknown']

match01 = pd.Categorical(user_ranks01, categories = lol_ranks, ordered = True)
match01

['silver', 'silver', 'silver', 'gold', 'bronze', 'bronze', 'diamond', 'silver', 'bronze', NaN]
Categories (9, object): ['iron' < 'bronze' < 'silver' < 'gold' ... 'diamond' < 'master' < 'grandmaster' < 'challenger']

In [24]:
# 코드를 본다면 unknown은 '-1' 로 되어있다. 
match01.codes

array([ 2,  2,  2,  3,  1,  1,  5,  2,  1, -1], dtype=int8)

# Renaming Categories
---
범주 이름 변경

`Categorical`은 `.categories` 속성이나 `.rename_categories()` 메서드를 통해 범주 이름을 변경할 수 있게 해준다.  

## `.categories` attribute로 변경하기

category로 지정된 것의 순서에 맞게 지정 변경이 되며, 사용하면 바로 변경이 되기 때문에 되돌릴 수 없다는 것을 주의해야 한다. 

In [25]:
# create a categorical with 3 categories
cat = pd.Categorical(["a","b","c","a"], categories=["a", "b", "c"])
cat

['a', 'b', 'c', 'a']
Categories (3, object): ['a', 'b', 'c']

In [26]:
# renames the categories (and also the values) : 바로 변경이 되어버린다. 
cat.categories = ["bronze", "silver", "gold"]
cat

['bronze', 'silver', 'gold', 'bronze']
Categories (3, object): ['bronze', 'silver', 'gold']

## `.rename_categories()` method로 변경하기
즉석 변경을 원하지 않을 경우엔 `.rename_categories()`메서드를 사용하면 된다. 



In [27]:
# this also renames 
cat.rename_categories(["x", "y", "z"])

['x', 'y', 'z', 'x']
Categories (3, object): ['x', 'y', 'z']

In [28]:
# the rename is not done in-place : xyz로 넣었으나 inplace=True 옵션을 주지 않아서 변경 전 것이 그대로 유지됨.
cat

['bronze', 'silver', 'gold', 'bronze']
Categories (3, object): ['bronze', 'silver', 'gold']

# `.add_categories()` : Appending new categories
--- 
새 범주 추가

`.add_categories()` 메서드를 사용해 범주를 추가할 수 있다.

metals에 백금을 추가하는 예시이다. 이 또한 `inplace = True` 옵션을 주지 않으면 바로 변경되지는 않는다.

In [29]:
# add a new platimnum category
metals_with_platinum = metals.add_categories(["platinum"])
metals_with_platinum

['bronze', 'gold', 'silver', 'bronze']
Categories (4, object): ['bronze' < 'silver' < 'gold' < 'platinum']

In [32]:
# 추가는 했지만 즉석 변경은 안됨
metals.categories

Index(['bronze', 'silver', 'gold'], dtype='object')

# `.remove_categories()` : Removing Categories
---
범주 삭제 

`.remove_categories()` 메서드를 통해 범주를 지정 삭제할 수 있다.  
**삭제된 범주는 `np.NaN`으로 처리된다.**  
이 또한 즉석 변경은 일어나지 않고, `inplace=True` 옵션을 써야 한다. 

In [33]:
# remove bronze category
metals_without_bronze = metals.remove_categories(["bronze"])
metals_without_bronze

[NaN, 'gold', 'silver', NaN]
Categories (2, object): ['silver' < 'gold']

In [34]:
# 삭제 되었지만 즉석 변경은 안됨
metals.categories

Index(['bronze', 'silver', 'gold'], dtype='object')

# `.remove_unused_categories()` : Removing unused categories
---
미사용 범주 삭제

사용되지 않는 범주의 경우 `.remove_unused_categories()`로 삭제할 수 있다. 즉석 변경은 일어나지 않는다.   
platinum 이 사용되지 않기 때문에 삭제할 수 있다.  

`inplace=True`옵션을 써야만 변경할 수 있다. 

In [35]:
# remove any unused categories (in this case, platinum)
metals_with_platinum.remove_unused_categories()

['bronze', 'gold', 'silver', 'bronze']
Categories (3, object): ['bronze' < 'silver' < 'gold']

In [36]:
# 즉석 변경 없기 때문에 유지됨
metals_with_platinum.categories

Index(['bronze', 'silver', 'gold', 'platinum'], dtype='object')

# `.set_categories()` : Setting categories
---
범주 설정

`.set_categories()` 메서드를 사용하면 범주를 삭제하고 추가하는 작업을 한 번에 할 수 있다.  
처음에 리스트로 주어주고 dtype을 category로 설정하면 카테고리 데이터가 되는데, `.set_categories([범주리스트])`로 넣어주면 해당 범주리스트만 사용하는 데이터로 변형된다.  
따라서 넣어준 범주리스트에 없는 값들은 `NaN`으로 대체된다. 

예시 `Series` s 이다. 

In [37]:
# sample Series
s = pd.Series(["one", "two", "four", "five"], dtype = "category")
s

0     one
1     two
2    four
3    five
dtype: category
Categories (4, object): ['five', 'four', 'one', 'two']

'one' 과 'four' 만 범주로 설정하면 두 가지는 `NaN`으로 대체된다. 

In [38]:
# remove the "two", "three" and "five" categories (replaced with NaN)
s = s.cat.set_categories(["one","four"])
s

0     one
1     NaN
2    four
3     NaN
dtype: category
Categories (2, object): ['one', 'four']

# 기술 통계 정보 : `Describe()`

`Categorial`의 `.describe()` 메서드는 `Series`나 `DataFrame`에서와 마찬가지로 기술 통계(descriptive statistics)정보를 출력한다.  

이 결과를 통해 각 범주에 해당하는 인스턴스의 수와 도수 분포(frequency distribution)을 알 수 있다.  
각 범주에 포함되는 값의 개수는 `.value_counts()`를 통해서도 알 수 있다. 

In [39]:
# get descriptive info on the metals categorical
metals.describe()

            counts  freqs
categories               
bronze           2   0.50
silver           1   0.25
gold             1   0.25

## Value counts 
각 범주에 포함되는 값의 개수는 `.value_counts()`를 통해서도 알 수 있다. 

In [40]:
# count the values in the categorical
metals.value_counts()

bronze    2
silver    1
gold      1
dtype: int64

## Minimum, maximum and mode
범주의 최솟값, 최댓값, 최빈값도 같은 이름의 메서드를 통해 알 수 있다. 

(`Categorical.mode`의 경우  사라질 것이며, `Series.mode`를 사용하라고 한다.)

In [41]:
# find the min, max and mode of the metals categorical
(metals.min(), metals.max(), metals.mode())

/var/folders/qw/j72d9nwn5dq0vxtqtw2bbtnh0000gp/T/ipykernel_5892/265606353.py:2: FutureWarning: Categorical.mode is deprecated and will be removed in a future version. Use Series.mode instead.
  (metals.min(), metals.max(), metals.mode())


('bronze',
 'gold',
 ['bronze']
 Categories (3, object): ['bronze' < 'silver' < 'gold'])

In [42]:
(metals.min(), metals.max(), metals.mode)

('bronze',
 'gold',
 <bound method Categorical.mode of ['bronze', 'gold', 'silver', 'bronze']
 Categories (3, object): ['bronze' < 'silver' < 'gold']>)

# Example: Munging school grades
---
성적 데이터 가공 : 숫자 대신 범주를 기반으로 정보를 조직화하기 위해 `Categorical`을 적용해보기 

숫자로 된 학생들의 성적에 문자 등급을 할당하기  
숫자로 된 이 점수들을 문자 코드로 분류해야 한다. 각 점수에 대한 구간을 정의하고, 구간별로 문자 등급을 연관시킨다. 

In [44]:
# 10 students with random grades 
np.random.seed(123456)
names = ['Ivana', 'Norris', 'Ruth', 'Lane', 'Skye', 'Sol', 
         'Dylan', 'Katina', 'Alissa', "Marc"]
grades = np.random.randint(50, 101, len(names))
scores = pd.DataFrame({'Name': names, 'Grade': grades})
scores

     Name  Grade
0   Ivana     51
1  Norris     92
2    Ruth    100
3    Lane     99
4    Skye     93
5     Sol     97
6   Dylan     93
7  Katina     77
8  Alissa     82
9    Marc     73

성적 구간을 만든다. 0-59] 는 F, 59~62] 까지 D- 이런 식이다. 

In [45]:
# bins and their mappings to letter grades
score_bins =    [ 0,  59,   62,  66,   69,   72,  76,   79,   82,  
                 86,   89,   92,  99, 100]
letter_grades = ['F', 'D-', 'D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 
                 'B+', 'A-', 'A', 'A+']

`pd.cut()`을 사용하여 각 점수에 문자 등급을 할당한다. 

파라미터에 대응한다면,  
- x = scores.Grade
- bins = score_bins
- labels = letter_grades
- ordered 는 default 값이 True이다. 위에 먹인 letter_grades는 자동적으로 순위를 갖는 `Categorial`이 되는 것이다!

In [46]:
# cut based upon the bins and assign the letter grade
letter_categories = pd.cut(scores.Grade, score_bins, labels = letter_grades)
scores['Letter'] = letter_categories # scores 에 등급 칼럼 넣기
scores

     Name  Grade Letter
0   Ivana     51      F
1  Norris     92     A-
2    Ruth    100     A+
3    Lane     99      A
4    Skye     93      A
5     Sol     97      A
6   Dylan     93      A
7  Katina     77     C+
8  Alissa     82     B-
9    Marc     73      C

이  `Categorical`에서 생성된 코드와 그에 연결된 문자 등급을 확인할 수 있다.

In [47]:
# examine the underlying categorical
letter_categories

0     F
1    A-
2    A+
3     A
4     A
5     A
6     A
7    C+
8    B-
9     C
Name: Grade, dtype: category
Categories (13, object): ['F' < 'D-' < 'D' < 'D+' ... 'B+' < 'A-' < 'A' < 'A+']

각 등급별 학생 수를 알고 싶다면 `.value_counts()`를 사용한다. 

In [48]:
# how many of each grade occurred?
scores.Letter.value_counts()

A     4
F     1
C     1
C+    1
B-    1
     ..
D     0
D+    0
C-    0
B     0
B+    0
Name: Letter, Length: 13, dtype: int64

In [49]:
scores['Letter'].value_counts()

A     4
F     1
C     1
C+    1
B-    1
     ..
D     0
D+    0
C-    0
B     0
B+    0
Name: Letter, Length: 13, dtype: int64

문자 등급 `Categorial`에는 논리적인 순서가 있으므로, `Categorial`이 적용된 칼럼을 정렬해 학생들을 성적 순으로 나열시킬 수 있다. 

In [50]:
# and sort by letter grade instead of numeric grade, descending order!
scores.sort_values(by = ['Letter'], ascending = False)

     Name  Grade Letter
2    Ruth    100     A+
3    Lane     99      A
4    Skye     93      A
5     Sol     97      A
6   Dylan     93      A
1  Norris     92     A-
8  Alissa     82     B-
7  Katina     77     C+
9    Marc     73      C
0   Ivana     51      F

# my sample : 
한국 주가 데이터로 등락률을 기준으로(상당히 극단적...) 회사를 나누어보자. 기준은 2022-11-30 이다. 
출처 : https://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201040101

In [57]:
df_ko_221130 = pd.read_csv('/Users/Angela/Desktop/Personal/StockData/krx_20221130.csv', encoding = 'cp949')
df = df_ko_221130[df_ko_221130['시장구분'] == 'KOSPI'][['종목코드', '종목명', '종가', '등락률', '거래량', '거래대금', '시가총액', '상장주식수']]
df

        종목코드      종목명      종가    등락률       거래량  \
1     095570   AJ네트웍스    6110   0.49    110183   
2     006840    AK홀딩스   15150   2.02     14692   
6     027410      BGF    4365  18.29  11158585   
7     282330   BGF리테일  205500   3.27    215574   
9     138930  BNK금융지주    7390   1.23   1801684   
...      ...      ...     ...    ...       ...   
2665  005010      휴스틸    5420  -1.45    439253   
2673  000540     흥국화재    3165  -0.94     85333   
2674  000547  흥국화재2우B   19300  -0.26        76   
2675  000545    흥국화재우    6020   0.67       910   
2676  003280     흥아해운    1625  -0.91    426373   

             거래대금           시가총액      상장주식수  
1       674688330   286084222450   46822295  
2       221418900   200700549150   13247561  
6     49369104315   417803792715   95716791  
7     44268140500  3551842683000   17283906  
9     13323873630  2408661467940  325935246  
...           ...            ...        ...  
2665   2383570150   212399366500   39188075  
2673    269593750   20332797142

In [58]:
rate_bins = [-30, -20, -10, -5, -2, 0, 2, 5, 10, 20, 30]
letter_grades = ['절망', '통곡', '눈물', '불안', '설마', '안심', '미소', '행복', '입틀막', '풀매도']

In [59]:
cate_rate = pd.cut(x = df.등락률, bins = rate_bins, labels = letter_grades)
df['심리상태'] = cate_rate
df

        종목코드      종목명      종가    등락률  ...         거래대금  \
1     095570   AJ네트웍스    6110   0.49  ...    674688330   
2     006840    AK홀딩스   15150   2.02  ...    221418900   
6     027410      BGF    4365  18.29  ...  49369104315   
7     282330   BGF리테일  205500   3.27  ...  44268140500   
9     138930  BNK금융지주    7390   1.23  ...  13323873630   
...      ...      ...     ...    ...  ...          ...   
2665  005010      휴스틸    5420  -1.45  ...   2383570150   
2673  000540     흥국화재    3165  -0.94  ...    269593750   
2674  000547  흥국화재2우B   19300  -0.26  ...      1470100   
2675  000545    흥국화재우    6020   0.67  ...      5490510   
2676  003280     흥아해운    1625  -0.91  ...    691332165   

               시가총액      상장주식수  심리상태  
1      286084222450   46822295    안심  
2      200700549150   13247561    미소  
6      417803792715   95716791   입틀막  
7     3551842683000   17283906    미소  
9     2408661467940  325935246    안심  
...             ...        ...   ...  
2665   212399366500   39188075

오늘 사람들이 얼마나 울고 웃었는지 보자. 

In [63]:
df['심리상태'].value_counts()

안심     426
설마     273
미소     167
불안      34
행복      19
입틀막      9
눈물       8
풀매도      5
통곡       1
절망       0
Name: 심리상태, dtype: int64

극단적인 종목을 알아보자. 

In [70]:
pd.set_option('display.max_rows', 50)
df.loc[(df['심리상태'] == '행복')|(df['심리상태'] == '입틀막')|(df['심리상태'] == '풀매도')][['종목명', '심리상태']].sort_values(by = '심리상태', ascending = False)

            종목명 심리상태
1587       영진약품  풀매도
2338    포스코스틸리온  풀매도
2157    코오롱글로벌우  풀매도
358       금호건설우  풀매도
603       동부건설우  풀매도
1835      이엔플러스  입틀막
1099       성문전자  입틀막
1972       제주은행  입틀막
2101        케이카  입틀막
6           BGF  입틀막
472     다이나믹디자인  입틀막
2234       태영건설  입틀막
292      경동도시가스  입틀막
2235      태영건설우  입틀막
2280    티와이홀딩스우   행복
1896       일성건설   행복
1875     인천도시가스   행복
1861       인디에프   행복
2231       태양금속   행복
1220    신세계 I&C   행복
1788       율촌화학   행복
1322    아시아나IDT   행복
136    KISCO홀딩스   행복
1102       성신양회   행복
839   미래에셋글로벌리츠   행복
805        명문제약   행복
797       메리츠화재   행복
602        동부건설   행복
357        금호건설   행복
279        가온전선   행복
253         STX   행복
250      SNT중공업   행복
2611       현대차우   행복

In [71]:
df.loc[(df['심리상태'] == '절망')|(df['심리상태'] == '통곡')|(df['심리상태'] == '눈물')][['종목명', '심리상태']].sort_values(by = '심리상태', ascending = False)

           종목명 심리상태
242      SK케미칼   눈물
293     경동인베스트   눈물
346      그린케미칼   눈물
1104        성안   눈물
1731  유니드비티플러스   눈물
2495   한국화장품제조   눈물
2548      한진칼우   눈물
2645     효성중공업   눈물
645       두산밥캣   통곡

종목 하나는 완전히 난리가 난 것 같다. 나쁜 의미에서...

~그만알아보자.~
