# (단층) 퍼셉트론 실습

퍼셉트론은 신경망의 최소 단위이다. 입력값과 출력값이 존재하는데, 가중합 노드(뉴런에 해당)와 활성화 함수 노드가 있다. 이 둘을 하나의 노드라고 생각할 수도 있다. 이를 거치면서 최종 출력값을 반환한다.

출력값을 결정하는 활성화 함수에는 계단 함수, 시그모이드, 렐루, 리키 렐루 등이 있다.

퍼셉트론으로 데이터를 분류를 한다면, 가장 먼저 해야할 일은 데이터를 기존 행렬의 형태에서 벡터로 바꾸는 것이다. 

다음은 입력 데이터와 가중치 벡터, 편향을 이용해 가중합을 구한 후 함수를 통해 해당 벡터의 점수를 출력한다.

해당 점수에 따라서 활성화 함수에 따라 결과가 분류된다.

---

##### 12.2.3 넘파이를 활용하여 분류기를 구현해본다.

# 입력층

In [1]:
import numpy as np

# 입력층 - 행렬 데이터 생성
input_data = np.array([[2,3], [5, 1]])
print(input_data)

[[2 3]
 [5 1]]


## 벡터로 변환


In [2]:
# matrix -> vector
x = input_data.reshape(-1)
print(x)

[2 3 5 1]


# 가중치 및 편향

In [3]:
# 가중치 및 편향값 설정
# 1로 분류하기 위한 가중치 벡터 w1, 2로 분류하기 위한 가중치 벡터 w2 설정
# 각 점수의 편향 설정

w1 = np.array([2,1,-3,3])
w2 = np.array([1,-3,1,3])

b1 = 3
b2 = 3

# 가중합 

In [4]:
# 가중합 구하기

# 가중치 벡터를 합쳐 가중치 행렬 설정, 각 행은 분류되는 점수를 구하는 데 사용된다
W = np.array([w1, w2])
print(W)

[[ 2  1 -3  3]
 [ 1 -3  1  3]]


In [5]:
# 각 편향 점수를 합쳐 편향 벡터를 구함

b = np.array([b1, b2])
print(b)

[3 3]


In [6]:
# 가중합 구하기
# np.dot 으로 행렬 곱 수행

weight_sum = np.dot(W, x) + b
print(weight_sum)

[-2  4]


# 출력층


In [8]:
# 출력층

res = 1/(1 + np.exp(-weight_sum))      # sigmoid 함수에 가중합을 넣는다
print(res)

[0.11920292 0.98201379]


행렬의 각 행(데이터)에 대한 최종 점수가 출력되었다. 예시로 레몬과 포도를 이야기 했는데, 레몬의 스코어는 0.11, 포도의 스코어는 0.98인 것으로 나왔다.

# 시그모이드 함수를 활성화 함수로 쓰는 퍼셉트론 전체 코드


In [ ]:
import numpy as np

# input layer
input_data = np.array([[2,3], [5,1]])
x = input_data.reshape(-1)              # matrix to vector

# weight and bias nod
w1 = np.array([2,1,-3,3])
w2 = np.array([1,-3,1,3])
b1 = 3
b2 = 3

# weighted sum
W = np.array([w1, w2])
b = np.array([b1, b2])
weight_sum = np.dot(W, x) + b

# output(activation function: sigmoid)
res = 1/(1 + np.exp(-weight_sum))