# k-최근접 이웃 알고리즘 실습

##### 가장 가까이에 있는 k개의 데이터와 비교하여 가장 가까운 데이터 종류로 판별하는 알고리즘 

##### 연속형의 숫자라면 주변 k개의 데이터의 평균값으로 예측하는 방법을 사용한다.
---

##### 8.3.2 붓꽃 데이터를 사용하여 꽃의 종류를 구분하는 모형을 만들어본다.

# Dataset import
## 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np

In [2]:
# pandas, numpy 불러오지 않고 쓰면 긴 메세지가 뜨는 것을 확인할 수 있었다.

from sklearn import datasets
raw_iris = datasets.load_iris()

In [3]:
# 데이터 셋 내 피처 살펴보기
raw_iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

# 피처, 타깃 데이터 지정

In [4]:
X = raw_iris.data
y = raw_iris.target

## 트레이닝, 테스트 데이터 분할

In [5]:
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state = 1)

## 데이터 표준화

In [6]:
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)                               # X 트레이닝 데이터 기준으로 std scaler fitting, Xtn Xte모두.
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

# k=2 k-nn 분류 모델

2개의 근접한 데이터를 보고 분류를 하는 모델을 만들어본다.


## 모델링
### 데이터 학습

In [7]:
from sklearn.neighbors import KNeighborsClassifier  # KN분류기를 import
clf_knn = KNeighborsClassifier(n_neighbors = 2)     # 2개의 이웃을 기준으로 판별
clf_knn.fit(X_tn_std, y_tn)

KNeighborsClassifier(n_neighbors=2)

### 데이터 예측

In [8]:
knn_pred = clf_knn.predict(X_te_std)
print(knn_pred)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]


0, 1, 2 각각 붓꽃의 종류가 정해져있을 것이다. 그에 따라 test데이터가 라벨링 된 것을 볼 수 있다.

## 정확도 평가

앞서 만든 모형의 정확도를 평가해보기로 한다. 평가하는 것은 sklearn.metrics의 accuracy_score를 활용한다.

In [9]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_te, knn_pred)
accuracy

1.0

어.... 어 왜째서 

### confusion matrix 확인

confusion matrix를 통해 예측값과 실제값의 일치 정도를 확인해본다.

In [10]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_te, knn_pred)
conf_matrix

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

잘못 분류된게 없...다. 

### 분류 리포트 확인


In [13]:
from sklearn.metrics import classification_report

class_rep = classification_report(y_te, knn_pred)
print(class_rep)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



무언가도 아무것도 말할게 없어져버리는 결과가 나왔다.

# 실험1: 데이터 표준화 없이 진행하기
---

## 모델링
### 데이터 학습

In [14]:
from sklearn.neighbors import KNeighborsClassifier       # KN분류기를 import
clf_knn_nstd = KNeighborsClassifier(n_neighbors = 2)     # 2개의 이웃을 기준으로 판별
clf_knn_nstd.fit(X_tn, y_tn)

KNeighborsClassifier(n_neighbors=2)

### 데이터 예측

In [17]:
knn_nstd_pred = clf_knn_nstd.predict(X_te)
print(knn_nstd_pred)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]


0, 1, 2 각각 붓꽃의 종류가 정해져있을 것이다. 그에 따라 test데이터가 라벨링 된 것을 볼 수 있다.

## 정확도 평가

앞서 만든 모형의 정확도를 평가해보기로 한다. 평가하는 것은 sklearn.metrics의 accuracy_score를 활용한다.

In [18]:
from sklearn.metrics import accuracy_score

accuracy_nstd = accuracy_score(y_te, knn_nstd_pred)
accuracy_nstd

1.0

(이러면 안되는데 틀려줘 제발)

### confusion matrix 확인

예측값과 실제값의 일치 정도를 확인해본다.

In [20]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_te, knn_nstd_pred)
conf_matrix

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

### 분류 리포트 확인


In [21]:
from sklearn.metrics import classification_report

class_rep = classification_report(y_te, knn_nstd_pred)
print(class_rep)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



### Commentary

데이터셋이 워낙 작은 것도 있고, 데이터 자체가 잘 되어있는 것인지 분류가 확실하게 잘 되었다. 그래서 표준화같은 과정을 거치지 않고도 좋은 결과를 보여주었다.



# 실험2: k = 3 k-nn 모델
---

이번에는 k가 2가 아니라 3인 모델로 확인해보려고 한다.

## 모델링

### 데이터 학습

In [22]:
from sklearn.neighbors import KNeighborsClassifier   # KN분류기를 import
clf_k3nn = KNeighborsClassifier(n_neighbors = 3)     # 2개의 이웃을 기준으로 판별
clf_k3nn.fit(X_tn_std, y_tn)

KNeighborsClassifier(n_neighbors=3)

### 데이터 예측

In [25]:
k3nn_pred = clf_k3nn.predict(X_te_std)
print(k3nn_pred)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]


## 정확도 평가

정확도와 confusion matrix로 확인해본다.

In [26]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_te, k3nn_pred)
accuracy

1.0

어.... 어 왜째서 또? 앙상블 할 때는 오히려 정확도가 이렇지 않았는데 아무래도 앙상블 모델에서는 과적합의 문제가 있었던 지도 모르겠다.

### confusion matrix 확인

confusion matrix를 통해 예측값과 실제값의 일치 정도를 확인해본다.

In [27]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_te, k3nn_pred)
conf_matrix

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

### 분류 리포트 확인

In [28]:
from sklearn.metrics import classification_report

class_rep = classification_report(y_te, k3nn_pred)
print(class_rep)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



### Commentary

k 를 2에서 3으로 바꾼 것은 데이터셋이 작기 때문에 결과를 크게 바뀔 수 있겠다 예상했지만 한 개도 틀리지 않았다. 

틀리게 하고싶지만 그것이야 말로 과대 적합을 만들어내는 것이라고 생각하기 떄문에 초심자는 이상한 객기를 버리기로 했다.