# 서포트 벡터 머신 실습

#####  

서포트 벡터 머신

> soft margin : 서포트 벡터 머신의 기준을 완화해 잘못 분류된 데이터를 어느 정도 허용하는 방법. 슬랙 변수의 합이 특정 상수 이하라는 제약 조건을 추가한다.

> kernel support vector machine: 평면이 아닌 상태로 분류한다고 가정. 서포트 벡터는 비선형이 된다.

> support vector regression: 서포트 벡터를 회귀 모형을 만드는데 활용하는 방법. 기존 모형은 트레이닝 데이터와 추정 직선과의 최소 제곱값을 최소화하는 방향으로 모델링을 했다면, 서포트 벡터 회귀는 서포트 벡터를 기준으로 회귀 모형을 만든다.

---

#####  8.8.5 와인을 분류하는 모형을 만들어본다. 


# Dataset import
## 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np

from sklearn import datasets
raw_wine = datasets.load_wine()

In [2]:
# 데이터 셋 내 피처 살펴보기
raw_wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [3]:
raw_wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

타깃 데이터는 1과 0으로 더미 변수 형태로 분류되어있다.

# 피처, 타깃 데이터 지정

In [4]:
X = raw_wine.data
y = raw_wine.target

## 트레이닝, 테스트 데이터 분할

In [6]:
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state = 0)

## 데이터 표준화

In [7]:
from sklearn.preprocessing import StandardScaler

# X 트레이닝 데이터 기준으로 Xtn Xte 를 표준화한다.
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

# 로지스틱 회귀 분류모델


## 모델링
### 데이터 학습 (kernel = 'linear')

In [9]:
from sklearn import svm
clf_svm_lr = svm.SVC(kernel = 'linear', random_state = 0)         # SVC 메소드를 이용해 분류 문제에 적용. 회귀라면 SVR.
clf_svm_lr.fit(X_tn_std, y_tn)

SVC(kernel='linear', random_state=0)

kernel 종류는 'linear', 'poly', 'rbf', 'sigmoid', 'precomputed' 등이 있다.

### 추정계수 및 상수항 확인

결국 선형으로 된 수식을 이용하기 때문에 있을 것이라 생각하여 구해본다.

In [11]:
# 추정계수 확인

print(clf_svm_lr.coef_)

[[ 0.63281625  0.4581143   0.61382651 -0.74067362  0.06223361 -0.03239475
   0.62034192  0.00335367 -0.08867444  0.10328628 -0.17104493  0.34739862
   0.99425411]
 [-0.07712273  0.00478948 -0.01729997 -0.12619677  0.02708887  0.25005098
   0.38033208 -0.1303428   0.15638472 -0.14453945  0.08315791  0.39489158
   0.16644915]
 [-0.3831114  -0.25485538 -0.33967811 -0.02691459  0.01221421 -0.13271982
   1.3614839   0.31866048  0.29768933 -1.07816467  0.50393183  0.98870524
  -0.27444806]]


In [12]:
# 상수항 확인

print(clf_svm_lr.intercept_)

[-0.53271006  0.27263187  1.76029582]


분류해야하는 각 클래스별로 존재하는 것을 알 수 있다.

### 데이터 예측

In [13]:
svm_lr_pred = clf_svm_lr.predict(X_te_std)
print(svm_lr_pred)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


## 평가

### 정확도 형가

accuracy를 확인해본다.

precision은 정밀도인데 이것도 확인해 볼 수 있을까? (average가 binary가 기본인데 이를 바꾸었더니 되었다.)

In [16]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_te, svm_lr_pred)
print(accuracy)

1.0


In [19]:
from sklearn.metrics import precision_score

precision = precision_score(y_te, svm_lr_pred, average = 'macro')
print(precision)

1.0


정확도가 굉장히 높다.

### confusion matrix 확인

In [20]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(y_te, svm_lr_pred)
print(conf_mat)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


### 분류 리포트 확인

In [21]:
from sklearn.metrics import classification_report

class_report = classification_report(y_te, svm_lr_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



SVM 자체는 과적합의 위험이 존재할 수 있다고 생각했는데 실제로도 그렇게 나온 것 같아서 조금 슬프다. 

