# 스칼라 연산

In [1]:
x = 2
y = 3

z = x + y

print(z)

5


In [2]:
x = 5
y = 1

z = x - y

print(z)

4


In [3]:
x = 6
y = 2

z = x * y

print(z)

12


In [4]:
x = 6
y = 2

z = x / y

print(z)

3.0


# 벡터의 연산

## 벡터의 덧셈

벡터의 덧셈은 더하고자 하는 두 벡터의 크기가 동일할 때만 연산이 가능하다. ()3차원 공간상의 벡터와 4차원 공간상 벡터는 덧셈이 불가하다.)

더하고자 하는 벡터를 구성하는 스칼라의 개수가 같아야 한다.

벡터의 덧셈은 교환 법칙이 성립한다. 

벡터의 덧셈 결과는 벡터의 시작 지점으로부터 평행사변형의 대각선을 구성하는 벡터이다.

In [5]:
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0,n):
    val = u[i] + v[i]
    w.append(val)

In [6]:
print(w)

[5, 7, 9]


함수로 정의하면 이와 같다.

In [7]:
def v_add(u, v):
    """
    벡터의 덧셈
    입력갑: 더하고자 하는 벡터 u, v
    출력값: 벡터 u, v의 덧셈 결과 w
    """
    n = len(u)
    w = []

    for i in range(0,n):
        val = u[i] + v[i]
        w.append(val)
    
    return w

In [8]:
u = [1, 2, 3]
v = [4, 5, 6]

v_add(u, v)

[5, 7, 9]

이를 넘파이로 수행하면 이와 같다.

In [27]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

w = u + v

In [28]:
print(w)

[5 7 9]


In [29]:
# 이때 w의 속성을 확인하면 ?

type(w)

numpy.ndarray

## 벡터의 뺄셈

벡터의 뺄셈은 덧셈과 마찬가지로 연산하고자 하는 두 벡터를 구성하는 스칼라의 개수가 동일할 때만 연산이 가능해진다.

벡터 a에서 벡터 b를 빼는 것을, -b 벡터를 더한다고 생각할 수도 있다. 

벡터는 위치에 영향을 받지 않는 다는 점을 이용한다. 

In [10]:
u = [7, 3, 9]
v = [2, 5, 7]

n = len(u)
w = []

for i in range(0,n):
    val = u[i] - v[i]
    w.append(val)

In [11]:
print(w)

[5, -2, 2]


이를 함수로 정의하면 이와 같다.

In [12]:
def v_substract(u, v):
    """
    벡터의 뺄셈
    입력값: 빼고자 하는 벡터 리스트 u, v
    출력값: 벡터 u, v의 뺄셈 결과 w
    """
    
    len(u)
    w = []
    
    for i in range(0, n):
        val = u[i] - v[i]
        w.append(val)
    
    return w

In [13]:
u = [7, 3, 9]
v = [2, 5, 7]
v_substract(u, v)

[5, -2, 2]

이를 넘파이로 수행하면 이와 같다.

In [30]:
import numpy as np

u = np.array([7, 3, 9])
v = np.array([2, 5, 7])

w = u - v

In [31]:
print(w)

[ 5 -2  2]


## 벡터의 곱셈

### 벡터의 스칼라의 곱

벡터의 스칼라 곱을 이용하면 벡터의 길이와 방향을 바꿀 수 있다. 벡터의 스칼라 곱은 벡터의 크기와 방향에 영향을 미친다.

In [14]:
u = [2, 4, 3]
a = 3

n = len(u)
w = []

for i in range(0, n):
    val = a * u[i]
    w.append(val)


In [15]:
print(w)

[6, 12, 9]


이를 함수로 정의하면 이와 같다.

In [16]:
def scalar_v_mul(a, u):
    """
    벡터의 스칼라 곱
    입력값: 스칼라 a, 벡터 리스트 u
    출력값: 스칼라 a와 벡터 리스트 u의 곱 결과
    """
    n = len(u)
    w = []
    
    for i in range(0, n):
        val = a * u[i]
        w.append(val)
    
    return w

In [17]:
u = [2, 4, 3]
a = 3

scalar_v_mul(a, u)

[6, 12, 9]

이를 넘파이로 수행하면 아래와 같다.

In [32]:
import numpy as np

u = np.array([1, 2, 4])
a = 3

w = a * u

In [33]:
print(w)

[ 3  6 12]


## 벡터 기본 연산의 성질

벡터 u, v, w와 스칼라 a, b 가 존재할 때 벡터의 기본 연산은 다음과 같은 성질이 성립한다.

u+v = v+u : 덧셈에는 교환 법칙이 성립한다.

(u+v)+w = u+(v+w) : 결합 법칙이 성립한다.

u+0 = 0+u = u : 벡터에 0을 더하면 기존 벡터와 동일하다.

u+(-u) = 0 : 자기 자신에 -1을 곱한 행렬을 더한 결과는 영 행렬이다.

a(bu) = (ab)u : 벡터 u에 스칼라 a, b를 곱할 때 스칼라 b에 먼저 벡터 u를 곱한 후 스칼라 a를 곱하는 것과, a와 b를 곱하고 벡터 u에 곱한 결과는 동일하다.

a(u+v) = au+av : 벡터 u와 v의 합에 스칼라 a를 곱한 결과는 각 벡터 u와 v에 스칼라 a 를 곱한 결과의 합과 같다.

(a+b)u = au+bu : 스칼라 a와 b의 합에 벡터 u를 곱한 결과는 각 스칼라와 u의 곱한 결과의 합과 같다.

# 벡터의 곱셈

여기서 벡터의 원소의 곱은 두 벡터의 동일한 위치의 원소를 곱하는 연산을 의미한다.

In [18]:
u = [1, 2, 4]
v = [7, 3, 2]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] * v[i]
    w.append(val)

In [19]:
print(w)

[7, 6, 8]


이를 함수로 만들면 다음과 같다.

In [20]:
def v_mul(u, v):
    """
    벡터의 원소 곱
    입력값: 원소 곱하고자 하는 벡터 리스트 u, v
    출력값: 벡터 u, v의 원소 곱 결과 w
    """
    n = len(u)
    w = []
    
    for i in range(0, n):
        val = u[i] * v[i]
        w.append(val)
    
    return w

In [21]:
u = [1, 2, 4]
v = [7, 3, 2]

v_mul(u, v)

[7, 6, 8]

이를 넘파이로 수행하면 이와 같다.

In [34]:
import numpy as np

u = np.array([1, 2, 4])
v = np.array([7, 3, 2])

w = u * v

In [35]:
print(w)

[7 6 8]


# 벡터의 나눗셈

여기서 벡터의 나눗셈은 동일한 위치의 원소끼리 나누는 것을 의미한다.

In [22]:
u = [6, 5, -9]
v = [2, 2, -3]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] / v[i]
    w.append(val)

In [23]:
print(w)

[3.0, 2.5, 3.0]


이를 함수로 구현하면 이와 같다.

In [25]:
def v_div(u, v):
    """
    벡터의 원소 나눗셈
    입력값: 원소 곱하고자 하는 벡터 리스트 u, v
    출력값: 벡터 u, v의 원소 나눗셈 결과 w
    """
    n = len(u)
    w = []
    
    for i in range(0, n):
        val = u[i] / v[i]
        w.append(val)
    
    return w

In [26]:
u = [6, 5, -9]
v = [2, 2, -3]

v_div(u, v)

[3.0, 2.5, 3.0]

이를 넘파이로 구현하면 이와 같다.

In [36]:
import numpy as np

u = np.array([6, 5, -9])
v = np.array([2, 2, -3])

w = u / v

In [37]:
print(w)

[3.  2.5 3. ]
