#  삼각 행렬

 ## 삼각 행렬의 개념
 
행렬의 구성 원소가 삼각형 형태로 되어있는 행렬. 정사각 행렬이다.

삼각형 형테를 제외한 나머지는 원소가 0이다. 

삼각행렬은 upper triangular matrix와 lower triangular matrix로, 

상 삼각 행렬은 주 대각 원소 아래쪽에 있는 모든 원소가 0인 정사각 행렬이고, 하 삼각 행렬은 주 대각 원소 위쪽에 있는 모든 원소가 0인 정사각 행렬이다.


## 삼각 행렬의 성질

- 같은 상 삼각 행렬 혹은 같은 하 삼각 행렬끼리의 덧셈과 뺄셈의 결과는 같은 상 삼각 행렬 혹은 하 삼각 행렬 형태이다.
- 상 삼각 행렬의 전치 행렬은 하 삼각 행렬이며, 하 삼각 행렬의 전치 행렬은 상 삼각 행렬이다.
- 삼각 행렬의 역행렬 또한 삼각 행렬이다.


## 삼각 행렬 만들기

### 상 삼각 행렬로 만들기

In [1]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
n = len(A)
p = len(A[0])
utri = []

for i in range(0, n):
    row = []
    for j in range(0, p):
        if i > j:
            row.append(0)
        else:
            row.append(A[i][j])
    utri.append(row)

In [3]:
print(utri)

[[1, 2, 3], [0, 5, 6], [0, 0, 9]]


### 상 삼각 행렬로 만드는 함수 만들기



In [5]:
def upper_tri(A):
    """
    상 삼각 행렬로 변환
    입력값: 변환하려는 행렬 A
    출력값: 행렬 A를 상 삼각 행렬로 변환한 행렬 utri
    """
    
    n = len(A)
    p = len(A[0])
    utri = []

    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i > j:
                row.append(0)
            else:
                row.append(A[i][j])
        utri.append(row)
    
    return utri

In [6]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
upper_tri(A)

[[1, 2, 3], [0, 5, 6], [0, 0, 9]]

## 하 삼각 행렬 만들기

### 상 삼각 행렬로 만드는 함수 만들기



In [7]:
def lower_tri(A):
    """
    하 삼각 행렬로 변환
    입력값: 변환하려는 행렬 A
    출력값: 행렬 A를 하 삼각 행렬로 변환한 행렬 utri
    """
    
    n = len(A)
    p = len(A[0])
    ltri = []

    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i < j:
                row.append(0)
            else:
                row.append(A[i][j])
        ltri.append(row)
    
    return ltri

In [8]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lower_tri(A)

[[1, 0, 0], [4, 5, 0], [7, 8, 9]]

In [3]:
import numpy as np

In [7]:
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
Z = np.zeros((4, 5))   # (n, p) 자체를 parameter로 넣어야 함