#  하우스홀더 행렬
 ## householder matrix의 개념
 
어떤 행렬을 다른 형태로 변환할 때 사용하는 행렬 중 하나이다. 

하우스 홀더 행렬은 정사각 행렬이다.

그리고 모든 열이 정규 직교(orthonomal)한다.

하우스홀더 행렬은 벡터와 단위행렬을 이용해 구할 수 있다.

하우스홀더 행렬을 구하기 위해 필요한 내적, 외적 결과를 같이 구한다.


# 하우스홀더 행렬 만들기
## 파이썬 실습

### 함수 만들기

벡터 v를 입력값으로 받아서 하우스홀더 행렬 H를 만드는 함수를 만든다.

In [1]:
def householder(v):
    """
    vector의 하우스홀더 행렬을 만든다
    입력값: 하우스홀더 행렬을 생성할 리스트v
    출력값: 리스트 v를 이용해 생성한 하우스홀더 행렬 H
    """
    
    n = len(A)
    outer_mat = outer_product(v, v)
    inner_val = inner_product(v, v)
    V = []
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            val = (2/inner_val) * outer_mat[i][j]
            row.append(val)
        V.append(row)
    H = substract(identity(n), V)
    
    return H

### 외적을 구하는 함수 만들기

In [2]:
def outer_product(a, b):
    """
    벡터의 외적
    입력값: 외적할 벡터 리스트 a, b
    출력값: 벡터 a, b의 외적 결과 res (matrix)
    """
    
    n1 = len(a)
    n2 = len(b)    
    res = []
    
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            val = a[i] * b[j]
            row.append(val)
        res.append(row)
    
    return res

### 내적을 구하는 함수 만들기

In [3]:
def inner_product(a, b):
    """
    벡터의 내적
    입력값: 내적할 벡터 리스트 a, b
    출력값: 벡터 a, b의 내적 결과 res (scalar)
    """
    
    n = len(a)
    res = 0
    
    for i in range(0, n):
        res += a[i] * b[i]
    
    return res

### n차원의 단위행렬 구하는 함수 만들기

In [4]:
def identity(n):
    """
    단위 행렬 생성
    입력값: 단위 행렬의 크기 n
    출력값: nxn 단위행렬 I
    """
    
    I = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        I.append(row)
    return I

### 행렬의 뺄셈구하는 함수 만들기

In [5]:
def substract(A, B):
    """
    행렬의 뺄셈
    입력값: 행렬의 뺄셈을 수행할 행렬 A , B
    출력값: 행렬 A - 행렬 B 결과인 행렬 res
    """
    
    n = len(A)
    p = len(A[0])
    
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    
    return res

### 하우스홀더 행렬을 구하는 전체 함수 코드 without numpy

In [9]:
def inner_product(a, b):
    """
    벡터의 내적
    입력값: 내적할 벡터 리스트 a, b
    출력값: 벡터 a, b의 내적 결과 res (scalar)
    """
    
    n = len(a)
    res = 0
    
    for i in range(0, n):
        res += a[i] * b[i]
    
    return res

def outer_product(a, b):
    """
    벡터의 외적
    입력값: 외적할 벡터 리스트 a, b
    출력값: 벡터 a, b의 외적 결과 res (matrix)
    """
    
    n1 = len(a)
    n2 = len(b)    
    res = []
    
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            val = a[i] * b[j]
            row.append(val)
        res.append(row)
    
    return res

def identity(n):
    """
    단위 행렬 생성
    입력값: 단위 행렬의 크기 n
    출력값: nxn 단위행렬 I
    """
    
    I = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        I.append(row)
    return I

def substract(A, B):
    """
    행렬의 뺄셈
    입력값: 행렬의 뺄셈을 수행할 행렬 A , B
    출력값: 행렬 A - 행렬 B 결과인 행렬 res
    """
    
    n = len(A)
    p = len(A[0])
    
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    
    return res

def householder(v):
    """
    vector의 하우스홀더 행렬을 만든다
    입력값: 하우스홀더 행렬을 생성할 리스트v
    출력값: 리스트 v를 이용해 생성한 하우스홀더 행렬 H
    """
    
    n = len(v)
    outer_mat = outer_product(v, v)
    inner_val = inner_product(v, v)
    V = []
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            val = (2/inner_val) * outer_mat[i][j]
            row.append(val)
        V.append(row)
    H = substract(identity(n), V)
    
    return H


구해볼까

In [10]:
cute_vector = [2,5,9,14,20]

In [11]:
householder(cute_vector)

[[0.9886685552407932,
  -0.028328611898016998,
  -0.0509915014164306,
  -0.07932011331444759,
  -0.11331444759206799],
 [-0.028328611898016998,
  0.9291784702549575,
  -0.1274787535410765,
  -0.19830028328611898,
  -0.28328611898017],
 [-0.0509915014164306,
  -0.1274787535410765,
  0.7705382436260624,
  -0.3569405099150142,
  -0.509915014164306],
 [-0.07932011331444759,
  -0.19830028328611898,
  -0.3569405099150142,
  0.4447592067988668,
  -0.7932011331444759],
 [-0.11331444759206799,
  -0.28328611898017,
  -0.509915014164306,
  -0.7932011331444759,
  -0.1331444759206799]]

## 넘파이 수행

In [12]:
import numpy as np

##### 1. 먼저 벡터를 선언한다.

In [13]:
v = np.array([2, 5, 9, 14, 20])

##### 2. 벡터의 길이를 구한다.

In [14]:
n = len(v)
print(n)

5


##### 3. 넘파이의 outer 함수를 통해 벡터 v와 자기자신의 외적 행렬을 구한다.

In [15]:
outer_mat = np.outer(v, v)
print(outer_mat)

[[  4  10  18  28  40]
 [ 10  25  45  70 100]
 [ 18  45  81 126 180]
 [ 28  70 126 196 280]
 [ 40 100 180 280 400]]


##### 4. 넘파이의 inner 함수를 통해 벡터 v와 자기 자신의 내적값을 구한다.

In [16]:
inner_val = np.inner(v, v)
print(inner_val)

706


##### 5. 하우스홀더 행렬을 구하기 위해 필요한 n차원 단위 행렬을 넘파이의 identity 함수를 이용해 구한다.

In [18]:
I = np.identity(n)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##### 6. 마지막으로 하우스 홀더 행렬을 구한다.

결과를 보면 약간의 차이가 있는데 올림의 차이로 보인다.

In [19]:
H = I - (2/inner_val) * outer_mat
print(H)

[[ 0.98866856 -0.02832861 -0.0509915  -0.07932011 -0.11331445]
 [-0.02832861  0.92917847 -0.12747875 -0.19830028 -0.28328612]
 [-0.0509915  -0.12747875  0.77053824 -0.35694051 -0.50991501]
 [-0.07932011 -0.19830028 -0.35694051  0.44475921 -0.79320113]
 [-0.11331445 -0.28328612 -0.50991501 -0.79320113 -0.13314448]]


### 전체 코드 with numpy

In [20]:
import numpy as np

v = np.array([2,5,9,14,20])

n = len(v)
outer_mat = np.outer(v, v)
inner_val = np.inner(v, v)
I = np.identity(n)
H = I-(2/inner_val) * outer_mat

In [21]:
H

array([[ 0.98866856, -0.02832861, -0.0509915 , -0.07932011, -0.11331445],
       [-0.02832861,  0.92917847, -0.12747875, -0.19830028, -0.28328612],
       [-0.0509915 , -0.12747875,  0.77053824, -0.35694051, -0.50991501],
       [-0.07932011, -0.19830028, -0.35694051,  0.44475921, -0.79320113],
       [-0.11331445, -0.28328612, -0.50991501, -0.79320113, -0.13314448]])