# 대칭 행렬

## 대칭 행렬의 개념

대칭행렬(symmetric matrix)은 기존 행렬과 전치 행렬이 동일한 정사각 행렬을 의미한다.

행렬 A가 다음을 만족하면 대칭 행렬이라고 할 수 있다.

$ A = A^T $ 즉, $ A_{ij} = A_{ji} $

대칭 행렬은 기존 행렬의 전치 행렬을 구해도 기존 행렬과 동일한 것을 의미한다.

우선 전치 행렬과 같다는 말은 i = j 라는 말이다. 행렬의 행의 크기와 열의 크기가 같을 것.

성질: 유한 차원 벡터 공간의 대칭 쌍선형 형식은 대칭 행렬의 개념과 일치한다. *(출처: https://ko.wikipedia.org/wiki/%EB%8C%80%EC%B9%AD%ED%96%89%EB%A0%AC)*



## 대칭 행렬의 성질

1. 대칭 행렬 간의 덧셈이나 뺼셈 또한 대칭 행렬이다.

2. 대칭 행렬끼리 곱한 결과는 대칭 행렬이 아니다. 

3. 행렬 $ A $ 가 대칭 행렬일 때 대칭 행렬 A의 거듭 제곱 형태인 $ A^n $ 또한 대칭 행렬이다.

4. 행렬 $ A $ 가 대칭 행렬이 아니더라도, $ A A^T $ 와 $ A^T A $ 는 대칭 행렬이다. (중요)

## 파이썬 실습

대칭 행렬의 성질을 확인할 것인데, 여기에는 전치 행렬을 만드는 함수와 행렬 곱을 수행하는 함수가 필요하다.

In [1]:
# 행렬의 전치 행렬

def transpose(A):
    """
    행렬의 전치 행렬
    입력값: 전치 행렬을 구하고자 하는 행렬 A
    출력값: 행렬 A의 전치 행렬 At
    """
    
    n = len(A)
    p = len(A[0])
    
    At = []
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    
    return At


In [2]:
# 행렬 A 와 B의 행렬 곱

def matmul(A, B):
    """
    행렬의 행렬 곱
    입력값: 행렬 곱을 수행할 행렬 A, B
    출력값: 행렬 A와 B의 행렬 곱 결과인 행렬 res
    """
    
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])

    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    
    return res


### 실험 1. 대칭 행렬 $ A $의 전치 행렬 $ A^T $ 는 기존 $ A $와 동일한가?

In [3]:
A = [[1, 0, 2], [0, 2, 1], [2, 1, 1]]

In [4]:
At = transpose(A)
print(At)

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]


In [5]:
A == At 

True

### 실험2. 대칭 행렬 $ A $ 의 거듭 제곱도 대칭 행렬인가?

In [6]:
AA = A

for i in range(0, 9):
    AA = matmul(AA, A)
    print('행렬 A의', i + 2, '제곱은', AA)

행렬 A의 2 제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]]
행렬 A의 3 제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]]
행렬 A의 4 제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]]
행렬 A의 5 제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]]
행렬 A의 6 제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]]
행렬 A의 7 제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]]
행렬 A의 8 제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]]
행렬 A의 9 제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]]
행렬 A의 10 제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]]


10 제곱 까지 살펴본 결과 모두 대칭 행렬이다.

### 실험3. 행렬 $A$와 그의 전치 행렬 $A^T$의 곱이 대칭 행렬인가?

In [13]:
# 대칭행렬이 아닌 A 와 A^T

A = [[1, 0, 3], [2, 1, 4], [5, 1, 0]]
At = transpose(A)
print(A,'||',  At)

[[1, 0, 3], [2, 1, 4], [5, 1, 0]] || [[1, 2, 5], [0, 1, 1], [3, 4, 0]]


In [14]:
# 둘의 곱 A * A^T

matmul(A, At)

[[10, 14, 5], [14, 21, 11], [5, 11, 26]]

In [15]:
# 둘의 곱 A^T * A

matmul(At, A)

[[30, 7, 11], [7, 2, 4], [11, 4, 25]]

대칭행렬이 나왔다.

## 넘파이 실습

In [16]:
import numpy as np

### 실험 1. 대칭 행렬 $ A $의 전치 행렬 $ A^T $ 는 $ A $와 동일한가?

In [17]:
A = np.array([[1, 0, 2], [0, 2, 1], [2, 1, 1]])
print(A)

[[1 0 2]
 [0 2 1]
 [2 1 1]]


In [19]:
At = np.transpose(A)
print(At)

[[1 0 2]
 [0 2 1]
 [2 1 1]]


In [20]:
A == At

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 실험 2. 대칭 행렬 A의 거듭 제곱도 대칭 행렬인가?

In [21]:
AA = A
for i in range(0, 9):
    AA = np.matmul(AA, A)
    print('행렬 A의', i+2, '제곱은')
    print(AA)
    print('--------------------')

행렬 A의 2 제곱은
[[5 2 4]
 [2 5 3]
 [4 3 6]]
--------------------
행렬 A의 3 제곱은
[[13  8 16]
 [ 8 13 12]
 [16 12 17]]
--------------------
행렬 A의 4 제곱은
[[45 32 50]
 [32 38 41]
 [50 41 61]]
--------------------
행렬 A의 5 제곱은
[[145 114 172]
 [114 117 143]
 [172 143 202]]
--------------------
행렬 A의 6 제곱은
[[489 400 576]
 [400 377 488]
 [576 488 689]]
--------------------
행렬 A의 7 제곱은
[[1641 1376 1954]
 [1376 1242 1665]
 [1954 1665 2329]]
--------------------
행렬 A의 8 제곱은
[[5549 4706 6612]
 [4706 4149 5659]
 [6612 5659 7902]]
--------------------
행렬 A의 9 제곱은
[[18773 16024 22416]
 [16024 13957 19220]
 [22416 19220 26785]]
--------------------
행렬 A의 10 제곱은
[[63605 54464 75986]
 [54464 47134 65225]
 [75986 65225 90837]]
--------------------


### 실험3. 행렬 $A$와 그의 전치 행렬 $A^T$의 곱이 대칭 행렬인가?

In [24]:
A = np.array([[1, 0, 3], [2, 1, 4], [5, 1, 0]])
print(A)

[[1 0 3]
 [2 1 4]
 [5 1 0]]


In [25]:
At = np.transpose(A)
print(At)

[[1 2 5]
 [0 1 1]
 [3 4 0]]


In [26]:
mul1 = np.matmul(A, At)
mul2 = np.matmul(At, A)
print(mul1)
print('----------------')
print(mul2)

[[10 14  5]
 [14 21 11]
 [ 5 11 26]]
----------------
[[30  7 11]
 [ 7  2  4]
 [11  4 25]]
