#  대각 행렬

 ## 대각 행렬의 개념
 
 대각 행렬은 행렬의 주 대각 원소가 아닌 원소가 0인 정사각 행렬이다.
 
 헹렬 내에 행 번호와 열 번호가 동일한 원소를 주 대각 원소라고 부른다. 주 대각 원소를 제외한 다른 원소가 0일 때 행렬  $$ D $$ 를 대각 행렬이라고 한다.
 
 주로 D 로 표현하는데, 이는 diagonal matrix 의 약자이다.
 
 대각 행렬  D 의 역행렬은 대각 행렬 D^{-1}의 주 대각 원소들의 역수로 구성되어 있다.
 
 
 
 

## 대각 행렬의 성질


## 대각 행렬 구하기

### 파이썬 구현

In [1]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# 이 행렬을 대각 행렬로 만드는, 즉 대각 원소를 제외한 나머지 원소를 0으로 바꾸는 것.

In [2]:
n = len(A)
D = []

for i in range(0, n):
    row = []
    for j in range(0, n):
        if i == j:
            row.append(A[i][j])
        else:
            row.append(0)
    D.append(row)
    

In [3]:
print(D)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


### 함수 만들기


In [4]:
def diag(A):
    """
    행렬의 대각 행렬
    입력값: 대각 행렬을 구하고자 하는 행렬  A
    출력값: 행렬 A의 대각 행렬 D
    """
    
    n = len(A)
    D = []

    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(A[i][j])
            else:
                row.append(0)
        D.append(row)
        
    return D

In [5]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

diag(A)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]

### 넘파이 수행

In [6]:
import numpy as np

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.diag(A)

print(D)

[1 5 9]


먼저 행렬을 diag 한 다음, 그 결과를 diag를 하면 된다.

In [8]:
np.diag(D)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

## 대각 원소 구하기

### 파이썬 함수로 구현

In [9]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
def diag_ele(A):
    """
    행렬의 대각 원소 구하기
    입력값: 대각 원소를 구하고자 하는 행렬  A
    출력값: 행렬 A의 대각 원소 리스트 d
    """
    
    n = len(A)
    d = []

    for i in range(0, n):
        d.append(A[i][i])
        
    return d

In [13]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

diag_ele(A)

[1, 5, 9]

### 넘파이 수행

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.diag(A)

print(d)

[1 5 9]
