#  대각 행렬

 ## 대각 행렬의 개념
 
 대각 행렬은 행렬의 주 대각 원소가 아닌 원소가 0인 정사각 행렬이다.
 
 헹렬 내에 행 번호와 열 번호가 동일한 원소를 주 대각 원소라고 부른다. 주 대각 원소를 제외한 다른 원소가 0일 때 행렬  $$ D $$ 를 대각 행렬이라고 한다.
 
 주로 D 로 표현하는데, 이는 diagonal matrix 의 약자이다.
 
 대각 행렬  D 의 역행렬은 대각 행렬 D^{-1}의 주 대각 원소들의 역수로 구성되어 있다.
 
 
 
 

## 대각 행렬의 성질


## 대각 행렬 구하기

### 파이썬 구현

In [1]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# 이 행렬을 대각 행렬로 만드는, 즉 대각 원소를 제외한 나머지 원소를 0으로 바꾸는 것.

In [2]:
n = len(A)
D = []

for i in range(0, n):
    row = []
    for j in range(0, n):
        if i == j:
            row.append(A[i][j])
        else:
            row.append(0)
    D.append(row)
    

In [3]:
print(D)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


### 함수 만들기


In [4]:
def diag(A):
    """
    행렬의 대각 행렬
    입력값: 대각 행렬을 구하고자 하는 행렬  A
    출력값: 행렬 A의 대각 행렬 D
    """
    
    n = len(A)
    D = []

    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(A[i][j])
            else:
                row.append(0)
        D.append(row)
        
    return D

In [5]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

diag(A)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]

### 넘파이 수행

In [6]:
import numpy as np

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.diag(A)

print(D)

[1 5 9]


먼저 행렬을 diag 한 다음, 그 결과를 diag를 하면 된다.

In [8]:
np.diag(D)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

## 대각 원소 구하기

### 파이썬 함수로 구현

In [9]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
def diag_ele(A):
    """
    행렬의 대각 원소 구하기
    입력값: 대각 원소를 구하고자 하는 행렬  A
    출력값: 행렬 A의 대각 원소 리스트 d
    """
    
    n = len(A)
    d = []

    for i in range(0, n):
        d.append(A[i][i])
        
    return d

In [13]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

diag_ele(A)

[1, 5, 9]

### 넘파이 수행

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.diag(A)

print(d)

[1 5 9]


## 대각 원소가 주어졌을 때, 대각 행렬로 변환

### 파이썬 함수로 구현

In [15]:
a = [1, 9, 5]

In [16]:
def ele2diag(a):
    """
    대각원소 -> 대각 행렬 반환
    입력값: 대각 원소 리스트 a
    출력값: 대각 원소 a를 이용해 생성한 nxn 대각 행렬 D
    n: 대각 원소 리스트 a의 길이
    """
    
    n = len(A)
    D = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(a[i])
            else:
                row.append(0)
        D.append(row)
    
    return D

In [17]:
ele2diag(a)

[[1, 0, 0], [0, 9, 0], [0, 0, 5]]

### 넘파이 수행

In [18]:
# 대각 원소 리스트 a
a = [1, 9, 5]

In [19]:
D = np.diag(a)

print(D)

[[1 0 0]
 [0 9 0]
 [0 0 5]]


## 일반 행렬에 대각 행렬을 곱했을 때

### 파이썬 실습


In [22]:
# 행렬 곱을 할 것이기에 이전 함수를 가져온다.

def matmul(A, B):
    """
    행렬의 행렬 곱
    입력값: 행렬 곱을 수행할 행렬 A, B
    출력값: 행렬 A와 B의 행렬 곱 결과인 행렬 res
    """
    
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])

    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    
    return res

In [20]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
D = ele2diag([2, 1, 1])

print(A)
print(D)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[2, 0, 0], [0, 1, 0], [0, 0, 1]]


In [23]:
# 파이썬의 리스트 자료구조를 이용해 행렬 A와 D를 선언하고 각각 A와 D라고 이름 짓는다.

AD = matmul(A, D)
print(AD)

[[2, 2, 3], [8, 5, 6], [14, 8, 9]]


결과를 확인하면 "행렬 A의 1열에만" 2가 곱해진 모습을 볼 수 있다.

반대로 곱하는 순서를 바꾸어 대각 행렬을 앞에다 곱하는 경우를 구해본다.

In [24]:
DA = matmul(D, A)
print(DA)

[[2, 4, 6], [4, 5, 6], [7, 8, 9]]


결과를 확인하면 "행렬 A의 1행에만" 2가 곱해진 모습을 볼 수 있다.

만약 2행 2열의 값이 3일 경우에는 어떻게 될까?

In [25]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
D_2 = ele2diag([1, 3, 1])

In [27]:
AD_2 = matmul(A, D_2)
print(AD_2)

[[1, 6, 3], [4, 15, 6], [7, 24, 9]]


In [28]:
D_2A = matmul(D_2, A)
print(D_2A)

[[1, 2, 3], [12, 15, 18], [7, 8, 9]]


각각 2열에만 3이 곱해지거나, 2행에만 3이 곱해진 것을 알 수 있다.

이제 이를 활용해서 1이아닌 다른 숫자들이 들어간 대각 행렬을 곱해본다.

In [29]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
D_3 = ele2diag([4, 3, 2])

In [30]:
AD_3 = matmul(A, D_3)
print(AD_3)

[[4, 6, 6], [16, 15, 12], [28, 24, 18]]


In [31]:
D_3A = matmul(D_3, A)
print(D_3A)

[[4, 8, 12], [12, 15, 18], [14, 16, 18]]


앞에 곱하면 열에 곱해지고, 뒤에 곱하면 행에 곱해진 것을 알 수 있다.