#  이중 대각 행렬

 ## 이중 대각 행렬의 개념
 
기존의 대각 행렬은 대각 원소를 제외한 나머지 행렬 원소가 모두 0이었다.

이중 대각 행렬은 대각 원소 뿐만 아니라 대각 원소의 바로 위쪽 혹은 아래쪽 원소가 0이 아닌 행렬이다.

삼각 행렬처럼 방향에 따라 upper bidiagonal matrix와 lower bidiagonal matrix로 나뉜다.

## 더하기공부 - 띠행렬

모든 0이 아닌 성분이 주대각선 주변에 집중된 희소 행렬(대부분의 원소가 0인 행렬)이다.

1행 1열을 중심으로 상 대역폭과 하 대역폭을 가지고 있으며, 상 대역폭이 1인 경우가 상 이중 대각 행렬과 같아지고, 하 대역폭이 1인 경우가 하 이중 대각 행렬과 같아진다!

이때 상 대역폭 = 1, 하 대역폭 = 1 일 때는 삼중 대각 행렬이 되고 

$ m \times n$ 행렬에서 상 대역폭 = 0, 하 대역폭 = n-1 일때 상 삼각 행렬이 된다.

마찬가지로 상 대역폭 = m-1, 하 대역폭 = 0 일때 하 삼각 행렬이 된다.

*참조 : https://ko.wikipedia.org/wiki/%EB%9D%A0%ED%96%89%EB%A0%AC*


# 이중 대각 행렬 만들기

## upper bidiagonal matrix 
### 파이썬으로 구현

이중 대각 행렬을 구성할 행렬을 선언한다.

In [1]:
# upper bidiagonal matrix

A = [[1, 2, 1, 4], [3, 6, 5, 7], [8, 10, 11, 9], [13, 14, 12, 15]]

이 행렬의 대각 원소와 대각 원소 바로 위쪽에 위치한 원소는 0이 아니도록 만들었다.

In [2]:
n = len(A)
p = len(A[0])

res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        if i > j or j - i >1:    # 행 번호가 열 번호보다 크거나(대각원소 아래), 열 번호- 행 번호의 차이가 1보다 큰 곳(대각원소의 대각선 윗 윗 방향 원소)
            row.append(0)
        else:
            row.append(A[i][j])
    res.append(row)

In [3]:
res

[[1, 2, 0, 0], [0, 6, 5, 0], [0, 0, 11, 9], [0, 0, 0, 15]]

### 함수 만들기

In [4]:
def upper_bidi(A):
    """
    upper bidiagonal 행렬 만들기
    입력값: 상 이중 대각 행렬 만드려는 행렬 A
    출력값: 행렬 A의 상 이중 대각 행렬 res
    """
    
    n = len(A)
    p = len(A[0])

    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i > j or j - i >1:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    
    return res

In [5]:
A = [[1, 2, 1, 4], [3, 6, 5, 7], [8, 10, 11, 9], [13, 14, 12, 15]]

In [6]:
upper_bidi(A)

[[1, 2, 0, 0], [0, 6, 5, 0], [0, 0, 11, 9], [0, 0, 0, 15]]

### 넘파이 실습

In [7]:
import numpy as np

In [8]:
A = np.array([[1, 2, 1, 4], [3, 6, 5, 7], [8, 10, 11, 9], [13, 14, 12, 15]])
print(A)

[[ 1  2  1  4]
 [ 3  6  5  7]
 [ 8 10 11  9]
 [13 14 12 15]]


1. diagonal 원소를 구한다.

In [9]:
diag_ele = np.diag(A)
print(diag_ele)

[ 1  6 11 15]


2. 다시 diag 하면 해당 원소로 n by n의 대각 행렬을 만든다.

In [10]:
diag_mat = np.diag(diag_ele)
print(diag_mat)

[[ 1  0  0  0]
 [ 0  6  0  0]
 [ 0  0 11  0]
 [ 0  0  0 15]]


3. 대각 원소 바로 위쪽에 존재하는 원소를 추출한다.

이때 diag 함수의 옵션에서 k 값을 조정하면 된다. 양수는 upper, 음수는 lower 원소를 찾으며,

k = 1은 대각 원소 위쪽으로 1번 쨰 위치한 원소를 추출한다는 의미이다.

In [11]:
u1_diag_ele = np.diag(A, k = 1)
print(u1_diag_ele)

[2 5 9]


In [12]:
u1_mat = np.diag(u1_diag_ele, k = 1)
print(u1_mat)

[[0 2 0 0]
 [0 0 5 0]
 [0 0 0 9]
 [0 0 0 0]]


4. 이 두 행렬을 더하면 완성!

In [13]:
upper_bidi = diag_mat + u1_mat
print(upper_bidi)

[[ 1  2  0  0]
 [ 0  6  5  0]
 [ 0  0 11  9]
 [ 0  0  0 15]]


## lower bidiagonal matrix

### 파이썬으로 구현

In [14]:
A = [[1, 2, 1, 4], [3, 6, 5, 7], [8, 10, 11, 9], [13, 14, 12, 15]]

In [15]:
n = len(A)
p = len(A[0])

res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        if i < j or i - j >1:    # 행 번호가 열 번호보다 크거나(대각원소 아래), 열 번호- 행 번호의 차이가 1보다 큰 곳(대각원소의 대각선 윗 윗 방향 원소)
            row.append(0)
        else:
            row.append(A[i][j])
    res.append(row)

In [16]:
res

[[1, 0, 0, 0], [3, 6, 0, 0], [0, 10, 11, 0], [0, 0, 12, 15]]

### 함수 만들기

In [18]:
def lower_bidi(A):
    """
    lower bidiagonal 행렬
    입력값: 행렬 A
    출력값: 행렬 A의 lower bidiagonal 행렬 res
    """
    n = len(A)
    p = len(A[0])
    
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i < j or i - j > 1:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    
    return res

In [19]:
lower_bidi(A)

[[1, 0, 0, 0], [3, 6, 0, 0], [0, 10, 11, 0], [0, 0, 12, 15]]

### 넘파이 실습

In [20]:
import numpy as np