# 전치 행렬

## 전치 행렬 개념

기존 행렬의 행과 열을 바꾼 행렬. 기존 행렬의 행 번호가 열 번호, 열 번호가 행 번호가 되어 원소의 자리가 바뀐 행렬.

헹렬의 크기도 기존의 행 크기가 열 크기로, 열 크기가 행 번호로 변환된다.





그 역함수 또한 (정의역과 공역이 뒤바뀐) 전치 행렬이다.

*이미지와 일부 출처: https://ko.wikipedia.org/wiki/%ED%96%89%EB%A0%AC*

## 전치 행렬의 성질

기존 행렬의 행 번호와 열 번호를 바꾼 행렬인데, 이러한 행렬의 특징을 가지고 있다.

$ ( A^T ) = A $

$ (A + B)^T = A^T + B^T $

$ (A - B)^T = A^T - B^T $

$ (aA)^T = aA^T $

$ (AB)^T = B^T A^T $

## 파이썬 실습

In [1]:
A = [[1, 5], [3, 4], [6, 2]]

n = len(A)
p = len(A[0])

At = []
for i in range(0, p):
    row = []
    for j in range(0, n):
        val = A[j][i]
        row.append(val)
    At.append(row)


In [2]:
print(At)

[[1, 3, 6], [5, 4, 2]]


## 함수 구현

In [5]:
def transpose(A):
    """
    행렬의 전치 행렬
    입력값: 전치 행렬을 구하고자 하는 행렬 A
    출력값: 행렬 A의 전치 행렬 At
    """
    
    n = len(A)
    p = len(A[0])
    
    At = []
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    
    return At

In [6]:
A = [[1, 5], [3, 4], [6, 2]]

transpose(A)

[[1, 3, 6], [5, 4, 2]]

## 넘파이 실습

In [7]:
import numpy as np

In [8]:
A = np.array([[1, 5], [3, 4], [6, 2]])
At = np.transpose(A)

In [9]:
print(At)

[[1 3 6]
 [5 4 2]]


.T  메소드를 이용해서 간단히 표현할 수도 있다.

In [10]:
Xt = A.T
print(Xt)

[[1 3 6]
 [5 4 2]]
