# 고윳값, 고유벡터 넘파이 실습

In [1]:
# 고유값 넘파이 실습
import pandas as pd
import numpy as np

A = np.array([[3, 2, -3], [5, 0, 4], [0, -1, 3]])

print(A)

[[ 3  2 -3]
 [ 5  0  4]
 [ 0 -1  3]]


In [2]:
e, v = np.linalg.eig(A)

In [3]:
print(e)

[ 5.33181031 -0.48705072  1.15524041]


In [4]:
print(v)

[[ 0.79156677 -0.29972355 -0.17536491]
 [ 0.56161668  0.91706148  0.86551759]
 [-0.24085007  0.26299058  0.46917636]]


고윳값 고유벡터 파이썬 실습

In [5]:
import copy

def eig_qr(A):
    n = len(A)
    E = copy.deepcopy(A)
    V = identity(n)
    for i in range(0, 30):
        Q, R = qr_gram(E)
        E = matmul(R, Q)
        V = matmul(V, Q)
    
    return E, V

In [6]:
E, V = eig_qr(A)

NameError: name 'identity' is not defined

# 특이값 분해 

## 넘파이 실습


# 파일을 직접 불러와서 직접 해보겠습니다.

In [7]:
import numpy as np
import pandas as pd

df = pd.read_csv('./data/star_classification.csv')

In [8]:
df

Unnamed: 0        obj_ID       alpha      delta         u         g  \
0               0  1.237661e+18  135.689107  32.494632  23.87882  22.27530   
1               1  1.237665e+18  144.826101  31.274185  24.77759  22.83188   
2               2  1.237661e+18  142.188790  35.582444  25.26307  22.66389   
3               3  1.237663e+18  338.741038  -0.402828  22.13682  23.77656   
4               4  1.237680e+18  345.282593  21.183866  19.43718  17.58028   
...           ...           ...         ...        ...       ...       ...   
99995       99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586   
99996       99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628   
99997       99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997   
99998       99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757   
99999       99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745   

              r         i         z  run_ID  rerun_ID  cam_col  field_ID  \
0      20.39501  19.16573  18.79371    3606       301        2        79   
1      22.58444  21.16812  21.61427    4518       301        5       119   
2      20.60976  19.34857  18.94827    3606       301        2       120   
3      21.61162  20.50454  19.25010    4192       301        3       214   
4      16.49747  15.97711  15.54461    8102       301        3       137   
...         ...       ...       ...     ...       ...      ...       ...   
99995  21.90404  21.30548  20.73569    7778       301        2       581   
99996  20.45003  19.75759  19.41526    7917       301        1       289   
99997  18.20428  17.69034  17.35221    5314       301        4       308   
99998  19.91386  19.07254  18.62482    3650       301        4       131   
99999  20.60115  20.00959  19.28075    3650       301        4        60   

        spec_obj_ID  class  redshift  plate    MJD  fiber_ID  
0      6.543777e+18      0  0.634794   5812  56354       171  
1      1.176014e+19      0  0.779136  10445  58158       427  
2      5.152200e+18      0  0.644195   4576  55592       299  
3      1.030107e+19      0  0.932346   9149  58039       775  
4      6.891865e+18      0  0.116123   6121  56187       842  
...             ...    ...       ...    ...    ...       ...  
99995  1.055431e+19      0  0.000000   9374  57749       438  
99996  8.586351e+18      0  0.404895   7626  56934       866  
99997  3.112008e+18      0  0.143366   2764  54535        74  
99998  7.601080e+18      0  0.455040   6751  56368       470  
99999  8.343152e+18      0  0.542944   7410  57104       851  

[100000 rows x 19 columns]

In [9]:
df.columns

Index(['Unnamed: 0', 'obj_ID', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z',
       'run_ID', 'rerun_ID', 'cam_col', 'field_ID', 'spec_obj_ID', 'class',
       'redshift', 'plate', 'MJD', 'fiber_ID'],
      dtype='object')

### 공분산행렬을 구하는 이유

통계학에서 엄청 중요하다. 선형대수에서 고유벡터 고윳값이 중요한 것처럼.

데이터가 어떻게 퍼져있느냐에 따라서 어떻게 차원축소할 것인지 정해지는데, 퍼짐을 나타내 주는게 공분산 행렬. 대각행렬이 분산을 이야기 한다.

이거 하나만 있으면.

In [10]:
cov = df.corr()

cov

Unnamed: 0    obj_ID     alpha     delta         u         g  \
Unnamed: 0     1.000000  0.001008 -0.008209  0.040398 -0.003319 -0.003336   
obj_ID         0.001008  1.000000 -0.013735 -0.301237  0.015310  0.015710   
alpha         -0.008209 -0.013735  1.000000  0.138691 -0.001532 -0.002423   
delta          0.040398 -0.301237  0.138691  1.000000  0.002074  0.003523   
u             -0.003319  0.015310 -0.001532  0.002074  1.000000  0.999311   
g             -0.003336  0.015710 -0.002423  0.003523  0.999311  1.000000   
r             -0.005429  0.153891 -0.022083 -0.006835  0.054149  0.062387   
i             -0.008272  0.147670 -0.023580 -0.004480  0.045730  0.056271   
z             -0.003810  0.013811 -0.002918  0.003630  0.998093  0.999161   
run_ID         0.001012  1.000000 -0.013737 -0.301238  0.015309  0.015710   
rerun_ID            NaN       NaN       NaN       NaN       NaN       NaN   
cam_col       -0.039816 -0.046997  0.019582  0.032565  0.003548  0.003508   
field_ID      -0.040603  0.031498 -0.165577 -0.173416 -0.008374 -0.008852   
spec_obj_ID    0.016059  0.239461 -0.002553  0.112329  0.029997  0.039443   
class         -0.009630 -0.036012 -0.011756  0.014452 -0.024645 -0.020066   
redshift      -0.001660  0.065400  0.001667  0.031638  0.014309  0.022954   
plate          0.016059  0.239460 -0.002554  0.112329  0.029997  0.039443   
MJD            0.016519  0.262687  0.019943  0.107333  0.031997  0.040274   
fiber_ID      -0.013032  0.067178  0.030464  0.028250  0.016305  0.017470   

                    r         i         z    run_ID  rerun_ID   cam_col  \
Unnamed: 0  -0.005429 -0.008272 -0.003810  0.001012       NaN -0.039816   
obj_ID       0.153891  0.147670  0.013811  1.000000       NaN -0.046997   
alpha       -0.022083 -0.023580 -0.002918 -0.013737       NaN  0.019582   
delta       -0.006835 -0.004480  0.003630 -0.301238       NaN  0.032565   
u            0.054149  0.045730  0.998093  0.015309       NaN  0.003548   
g            0.062387  0.056271  0.999161  0.015710       NaN  0.003508   
r            1.000000  0.962868  0.053677  0.153889       NaN  0.008480   
i            0.962868  1.000000  0.055994  0.147668       NaN  0.007615   
z            0.053677  0.055994  1.000000  0.013811       NaN  0.003365   
run_ID       0.153889  0.147668  0.013811  1.000000       NaN -0.047098   
rerun_ID          NaN       NaN       NaN       NaN       NaN       NaN   
cam_col      0.008480  0.007615  0.003365 -0.047098       NaN  1.000000   
field_ID    -0.026423 -0.026679 -0.008903  0.031498       NaN -0.015684   
spec_obj_ID  0.655245  0.661641  0.037813  0.239460       NaN -0.001946   
class       -0.076766  0.015028 -0.001614 -0.036014       NaN  0.023138   
redshift     0.433241  0.492383  0.030380  0.065400       NaN  0.000097   
plate        0.655243  0.661640  0.037813  0.239459       NaN -0.001949   
MJD          0.671180  0.672523  0.037469  0.262687       NaN -0.006745   
fiber_ID     0.223106  0.214787  0.014668  0.067165       NaN  0.121597   

             field_ID  spec_obj_ID     class  redshift     plate       MJD  \
Unnamed: 0  -0.040603     0.016059 -0.009630 -0.001660  0.016059  0.016519   
obj_ID       0.031498     0.239461 -0.036012  0.065400  0.239460  0.262687   
alpha       -0.165577    -0.002553 -0.011756  0.001667 -0.002554  0.019943   
delta       -0.173416     0.112329  0.014452  0.031638  0.112329  0.107333   
u           -0.008374     0.029997 -0.024645  0.014309  0.029997  0.031997   
g           -0.008852     0.039443 -0.020066  0.022954  0.039443  0.040274   
r           -0.026423     0.655245 -0.076766  0.433241  0.655243  0.671180   
i           -0.026679     0.661641  0.015028  0.492383  0.661640  0.672523   
z           -0.008903     0.037813 -0.001614  0.030380  0.037813  0.037469   
run_ID       0.031498     0.239460 -0.036014  0.065400  0.239459  0.262687   
rerun_ID          NaN          NaN       NaN       NaN       NaN       NaN   
cam_col     -0.015684    -0.001946 

다시

In [11]:
df

Unnamed: 0        obj_ID       alpha      delta         u         g  \
0               0  1.237661e+18  135.689107  32.494632  23.87882  22.27530   
1               1  1.237665e+18  144.826101  31.274185  24.77759  22.83188   
2               2  1.237661e+18  142.188790  35.582444  25.26307  22.66389   
3               3  1.237663e+18  338.741038  -0.402828  22.13682  23.77656   
4               4  1.237680e+18  345.282593  21.183866  19.43718  17.58028   
...           ...           ...         ...        ...       ...       ...   
99995       99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586   
99996       99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628   
99997       99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997   
99998       99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757   
99999       99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745   

              r         i         z  run_ID  rerun_ID  cam_col  field_ID  \
0      20.39501  19.16573  18.79371    3606       301        2        79   
1      22.58444  21.16812  21.61427    4518       301        5       119   
2      20.60976  19.34857  18.94827    3606       301        2       120   
3      21.61162  20.50454  19.25010    4192       301        3       214   
4      16.49747  15.97711  15.54461    8102       301        3       137   
...         ...       ...       ...     ...       ...      ...       ...   
99995  21.90404  21.30548  20.73569    7778       301        2       581   
99996  20.45003  19.75759  19.41526    7917       301        1       289   
99997  18.20428  17.69034  17.35221    5314       301        4       308   
99998  19.91386  19.07254  18.62482    3650       301        4       131   
99999  20.60115  20.00959  19.28075    3650       301        4        60   

        spec_obj_ID  class  redshift  plate    MJD  fiber_ID  
0      6.543777e+18      0  0.634794   5812  56354       171  
1      1.176014e+19      0  0.779136  10445  58158       427  
2      5.152200e+18      0  0.644195   4576  55592       299  
3      1.030107e+19      0  0.932346   9149  58039       775  
4      6.891865e+18      0  0.116123   6121  56187       842  
...             ...    ...       ...    ...    ...       ...  
99995  1.055431e+19      0  0.000000   9374  57749       438  
99996  8.586351e+18      0  0.404895   7626  56934       866  
99997  3.112008e+18      0  0.143366   2764  54535        74  
99998  7.601080e+18      0  0.455040   6751  56368       470  
99999  8.343152e+18      0  0.542944   7410  57104       851  

[100000 rows x 19 columns]

In [12]:
sub_df = df[['u','g','r','i','z']]

In [13]:
sub_df

u         g         r         i         z
0      23.87882  22.27530  20.39501  19.16573  18.79371
1      24.77759  22.83188  22.58444  21.16812  21.61427
2      25.26307  22.66389  20.60976  19.34857  18.94827
3      22.13682  23.77656  21.61162  20.50454  19.25010
4      19.43718  17.58028  16.49747  15.97711  15.54461
...         ...       ...       ...       ...       ...
99995  22.16759  22.97586  21.90404  21.30548  20.73569
99996  22.69118  22.38628  20.45003  19.75759  19.41526
99997  21.16916  19.26997  18.20428  17.69034  17.35221
99998  25.35039  21.63757  19.91386  19.07254  18.62482
99999  22.62171  21.79745  20.60115  20.00959  19.28075

[100000 rows x 5 columns]

In [14]:
sub_df_t = np.transpose(sub_df)

In [15]:
sub_df_t

0         1         2         3         4         5         6      \
u  23.87882  24.77759  25.26307  22.13682  19.43718  23.48827  21.46973   
g  22.27530  22.83188  22.66389  23.77656  17.58028  23.33776  21.17624   
r  20.39501  22.58444  20.60976  21.61162  16.49747  21.32195  20.92829   
i  19.16573  21.16812  19.34857  20.50454  15.97711  20.25615  20.60826   
z  18.79371  21.61427  18.94827  19.25010  15.54461  19.54544  20.42573   

      7         8         9      ...     99990     99991     99992     99993  \
u  22.24979  24.40286  21.74669  ...  23.79655  26.22899  25.82234  23.13172   
g  22.02172  22.35669  20.03493  ...  22.41332  21.84820  24.02722  23.18506   
r  20.34126  20.61032  19.17553  ...  20.36012  20.47138  21.43137  21.52854   
i  19.48794  19.46490  18.81823  ...  19.33964  19.60049  20.13085  20.26975   
z  18.84999  18.95852  18.65422  ...  18.74413  18.94726  19.66464  20.11383   

      99994     99995     99996     99997     99998     99999  
u  20.96526  22.16759  22.69118  21.16916  25.35039  22.62171  
g  19.81625  22.97586  22.38628  19.26997  21.63757  21.79745  
r  19.34186  21.90404  20.45003  18.20428  19.91386  20.60115  
i  19.14711  21.30548  19.75759  17.69034  19.07254  20.00959  
z  19.05790  20.73569  19.41526  17.35221  18.62482  19.28075  

[5 rows x 100000 columns]

공분산행렬

In [16]:
cov_df = sub_df_t.dot(sub_df)
cov_df

u             g             r             i             z
u  1.492419e+08  1.459268e+08  4.350137e+07  4.220479e+07  1.416397e+08
g  1.459268e+08  1.429609e+08  4.070286e+07  3.949792e+07  1.389820e+08
r  4.350137e+07  4.070286e+07  3.893961e+07  3.780759e+07  3.699218e+07
i  4.220479e+07  3.949792e+07  3.780759e+07  3.673218e+07  3.594145e+07
z  1.416397e+08  1.389820e+08  3.699218e+07  3.594145e+07  1.355190e+08

In [17]:
e, v = np.linalg.eig(cov_df)

In [18]:
e

array([4.52407691e+08, 5.07357218e+07, 2.04743727e+05, 4.06186418e+04,
       4.77288840e+03])

In [19]:
v

array([[-0.5733491 ,  0.0909501 , -0.67895384, -0.44905829,  0.01916291],
       [-0.56012813,  0.14008024, -0.03231131,  0.78254068, -0.23069477],
       [-0.18000134, -0.69174032, -0.04794331,  0.19084663,  0.67109898],
       [-0.17473995, -0.67196189,  0.16814737, -0.19588892, -0.67177911],
       [-0.54276399,  0.20510523,  0.71232406, -0.33343941,  0.21154596]])

In [20]:
corr_sub_df = sub_df.corr()
corr_sub_df

u         g         r         i         z
u  1.000000  0.999311  0.054149  0.045730  0.998093
g  0.999311  1.000000  0.062387  0.056271  0.999161
r  0.054149  0.062387  1.000000  0.962868  0.053677
i  0.045730  0.056271  0.962868  1.000000  0.055994
z  0.998093  0.999161  0.053677  0.055994  1.000000

svd

In [21]:
U, S, Vt = np.linalg.svd(cov_df)

In [22]:
U

array([[-0.5733491 , -0.0909501 ,  0.67895384,  0.44905829, -0.01916291],
       [-0.56012813, -0.14008024,  0.03231131, -0.78254068,  0.23069477],
       [-0.18000134,  0.69174032,  0.04794331, -0.19084663, -0.67109898],
       [-0.17473995,  0.67196189, -0.16814737,  0.19588892,  0.67177911],
       [-0.54276399, -0.20510523, -0.71232406,  0.33343941, -0.21154596]])

In [23]:
S

array([4.52407691e+08, 5.07357218e+07, 2.04743727e+05, 4.06186418e+04,
       4.77288840e+03])

In [24]:
Vt

array([[-0.5733491 , -0.56012813, -0.18000134, -0.17473995, -0.54276399],
       [-0.0909501 , -0.14008024,  0.69174032,  0.67196189, -0.20510523],
       [ 0.67895384,  0.03231131,  0.04794331, -0.16814737, -0.71232406],
       [ 0.44905829, -0.78254068, -0.19084663,  0.19588892,  0.33343941],
       [-0.01916291,  0.23069477, -0.67109898,  0.67177911, -0.21154596]])