# LU 분해

## 넘파이 실습

In [1]:
import numpy as np
from scipy.linalg import lu # lu분해는 scipy 안에 있음

In [2]:
A = np.array([[2,-2,-2],[0,-2,2],[-1,5,2]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [5]:
L

array([[ 1. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ],
       [ 0. , -0.5,  1. ]])

In [6]:
U

array([[ 2. , -2. , -2. ],
       [ 0. ,  4. ,  1. ],
       [ 0. ,  0. ,  2.5]])

In [7]:
# A = LU 확인

L@U

array([[ 2., -2., -2.],
       [-1.,  5.,  2.],
       [ 0., -2.,  2.]])

L@U가 P에 의해서 행의 순서가 바뀐 것이 반영되서 나온다.

# 텐서 실습

### 각 원소에 접근하기

In [10]:
# 벡터 : 리스트 한 겹
# 각 원소에 접근할 때 대괄호도 하나
x = [1, 2]

In [11]:
x[0]

1

In [12]:
x[1]

2

In [8]:
# 행렬 : 리스트 두 겹
# 각 원소에 접근할 때 대괄호가 둘
A = [[1, 2], [3, 4]]

In [13]:
A[0][0]

1

In [14]:
A[0][1]

2

In [15]:
A[1][0]

3

In [16]:
A[1][1]

4

### 텐서 만들기

In [19]:
# 텐서 : 리스트가 세 겹
T = [[[1, 2],[3, 4]], [[5, 6], [7, 8]]]

채널 번수가 맨 앞으로 온다는 것을 기억해야 한다.

In [20]:
T[0][0][0]

1

In [21]:
T[0][0][1]

2

In [22]:
T[0][1][0]

3

In [23]:
T[0][1][1]

4

In [24]:
T[1][0][0]

5

In [25]:
T[1][0][1]

6

In [26]:
T[1][1][0]

7

In [27]:
T[1][1][1]

8

## 텐서의 노름 구하기

In [28]:
A = [ [[1,0,1,0], [2,1,0,1], [3,4,0,2]],
      [[3,1,2,0], [1,0,4,2], [0,1,0,2]]  ]

In [29]:
print(A)

[[[1, 0, 1, 0], [2, 1, 0, 1], [3, 4, 0, 2]], [[3, 1, 2, 0], [1, 0, 4, 2], [0, 1, 0, 2]]]


In [32]:
n = len(A[0])    # 열 벡터의 개수
p = len(A[0][0]) # 행 벡터의 개수
q = len(A)       # 행렬이 몇 개

In [33]:
print(n, p, q)

3 4 2


In [35]:
norm = 0
for i in range(0, n):
    for j in range(0, p):
        for k in range(0, q):
            norm += A[k][i][j]**2

norm = norm**0.5

In [37]:
print(norm)

8.774964387392123


## 텐서의 내적 구하기

채널번호가 가장 앞에 오는거 까먹지 말기

### 파이썬으로 하기

In [38]:
A = [ [[1,0,1,0], [2,1,0,1], [3,4,0,2]],
      [[3,1,2,0], [1,0,4,2], [0,1,0,2]]  ]
B = [ [[2,1,3,1], [0,2,1,3], [1,0,1,1]],
      [[1,2,3,1], [3,1,0,3], [0,2,3,1]]  ]

In [39]:
n = len(A[0])
p = len(A[0][0])
q = len(A)

In [41]:
inner_product = 0
for i in range(0, n):
    for j in range(0, p):
        for k in range(0, q):
            inner_product += A[k][i][j] * B[k][i][j]

In [42]:
print(inner_product)

39


### 넘파이로 하기

In [43]:
import numpy as np

# 넣는 것 array로 안하고 리스트로 바로 넣어도 값은 같게 나올 수 있다.

In [44]:
A = np.array([ [[1,0,1,0], [2,1,0,1], [3,4,0,2]],
               [[3,1,2,0], [1,0,4,2], [0,1,0,2]]  ])
B = np.array([ [[2,1,3,1], [0,2,1,3], [1,0,1,1]],
               [[1,2,3,1], [3,1,0,3], [0,2,3,1]]  ])

In [45]:
C = np.multiply(A, B)

In [46]:
print(C)

[[[2 0 3 0]
  [0 2 0 3]
  [3 0 0 2]]

 [[3 2 6 0]
  [3 0 0 6]
  [0 2 0 2]]]


In [48]:
inner_product = np.sum(C)
print(inner_product)

39


간단한 행렬을 했지만, 실제 데이터로 하게되면 개념을 모르면 건드리기 힘들어진다.

# 유용한 함수 알아보기

## np.reshape

텐서를 자유롭게 변환하는 것이 쉬워져야 한다. 이때 사용하기 좋은 함수이다.

In [76]:
import numpy as np

A = np.array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]


In [51]:
A.shape

(8,)

In [50]:
A1 = A.reshape(8, 1) # 8행 1열로 만들기
print(A1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [52]:
A1.shape

(8, 1)

행 벡터는 리스트 하나로 표현되었지만, 열 벡터는 리스트 여러개로 표현되었다.

파이썬은 행 기준이다 보니까 1행 8열은 리스트 하나로 표현되지만 8열 1행은 여러 리스트로 될 수 밖에 없다. 

수행을 하다가 리스트가 여러개로 나올 경우 이런 상황을 떠올리면 된다.

In [53]:
# 2행 4열로 만들기 1

A2 = A.reshape(2, 4)
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
A2.shape

(2, 4)

In [56]:
# 2행 4열로 만들기 2

A3 = np.reshape(A, (2,4))

In [57]:
print(A3)

[[1 2 3 4]
 [5 6 7 8]]


### 행이나 열 파라미터에 -1 는 알아서하라는 와일드카드와 비슷하다.

In [78]:
A4 = A.reshape(-1, 4)
print(A4)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
A5 = np.reshape(A, (2, -1))
print(A5)

[[1 2 3 4]
 [5 6 7 8]]


### 그럼 그냥 -1을 넣어버리면?

이렇게 된다. 

가장 많이 쓰인다. 행과 열 입력값 두개를 넣어야 하는데, -1 하나만 넣을 떄가 있다.

행 벡터로, 하나의 행열을 한 줄로 바꿔버리는 것이다.

In [62]:
A6 = A5.reshape(-1)
print(A6)

[1 2 3 4 5 6 7 8]


### 

In [63]:
A7 = A.reshape(4, 2)
print(A7)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 행렬을 텐서로 만들려면

파라미터 세 개가 되는데, 맨 앞이 채널수가 되고, 다음이 행, 열 개수가 된다.

In [64]:
B = np.array([[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12], 
              [13, 16, 19, 22], [14, 17, 20, 23], [15, 18, 21, 24]])

In [65]:
print(B)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]
 [13 16 19 22]
 [14 17 20 23]
 [15 18 21 24]]


In [67]:
# (차원개수, 행 개수, 열 개수)

B1 = B.reshape(2, 3, 4)
print(B1)

[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[13 16 19 22]
  [14 17 20 23]
  [15 18 21 24]]]


### 행렬을 벡터로 만들려면

파라미터를 하나만 쓰면 벡터로 만들어진다. 

근데 행 기준으로 벡터화가 되는데, 이때 order = 'F' 를 넣으면 열 기준으로 벡터화를 시킬 수 있다.

In [68]:
C1 = B1[0].reshape(-1)
print(C1)

[ 1  4  7 10  2  5  8 11  3  6  9 12]


In [69]:
C2 = B1[0].reshape(-1, order='F')
print(C2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## np.concatenate

 행렬을 합치는 경우 사용한다.
 
 (A, B) axis = [0: 적 방향, 1: 횡방향, None: 펼쳐서 한 행으로 만듬]

In [70]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [71]:
print(A)

[[1 2]
 [3 4]]


In [72]:
print(B)

[[5 6]
 [7 8]]


In [73]:
C = np.concatenate((A, B), axis = 0)
print(C)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [74]:
D = np.concatenate((A, B), axis = 1)
print(D)

[[1 2 5 6]
 [3 4 7 8]]


In [75]:
E = np.concatenate((A, B), axis = None)
print(E)

[1 2 3 4 5 6 7 8]


# tensor to matrix

## 파이썬으로 해보기

In [88]:
tensor = np.array([[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]],
                   [[13, 16, 19, 22], [14, 17, 20, 23], [15, 18, 21, 24]]])

In [ ]:
n = len(tensor[0])
p = len(tensor[0][0])
q = len(tensor)

mode1 = []

for i in range(0, n):
    row = []
    

## 넘파이로 해보기

In [81]:
tensor = np.array([[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]],
                   [[13, 16, 19, 22], [14, 17, 20, 23], [15, 18, 21, 24]]])

### mode1

In [82]:
# 텐서 내의 행렬을 가로로 붙이기

mode1 = np.concatenate((tensor[0], tensor[1]), axis = 1)
print(mode1)

[[ 1  4  7 10 13 16 19 22]
 [ 2  5  8 11 14 17 20 23]
 [ 3  6  9 12 15 18 21 24]]


In [83]:
print(tensor[0])

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [84]:
print(tensor[0])

[[13 16 19 22]
 [14 17 20 23]
 [15 18 21 24]]


### mode2

In [87]:
# 텐서 내의 행렬을 전치한 후 가로로 붙이기

mode2 = np.concatenate((tensor[0].T, tensor[1].T), axis = 1)
print(mode2)

[[ 1  2  3 13 14 15]
 [ 4  5  6 16 17 18]
 [ 7  8  9 19 20 21]
 [10 11 12 22 23 24]]


### mode 3

In [89]:
# 텐서 내의 행렬을 일렬로 나열한 후(벡터로 만든 후) 열 방향으로 붙이기
# 이때 이 행렬의 경우에는 열 순으로 빼야하기 때문에 Transpose 하고 해도 되고
# order = 'F' 를 사용해도 된다.

ch1 = tensor[0].T.reshape(-1)
print(ch1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [90]:
ch2 = tensor[1].T.reshape(-1)
print(ch2)

[13 14 15 16 17 18 19 20 21 22 23 24]


In [94]:
mode3_ = np.concatenate((ch1, ch2), axis = 0)
print(mode3_)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [96]:
mode3 = mode3_.reshape(2, -1) # 2행으로 만들기
print(mode3)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


# 텐서 곱

행렬 * 텐서

## 파이썬으로 해보기

## 넘파이로 해보기

In [99]:
U = np.array([[1,3,5], [2,4,6]])

A = np.array([[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]],
                   [[13, 16, 19, 22], [14, 17, 20, 23], [15, 18, 21, 24]]])

In [106]:
UA1 = np.matmul(U, A[0])
print(UA1)

[[ 22  49  76 103]
 [ 28  64 100 136]]


In [109]:
UA2 = np.matmul(U, A[1])
print(UA2)

[[130 157 184 211]
 [172 208 244 280]]


In [110]:
# 

C = np.concatenate((UA1, UA2), axis=0)
print(C)

[[ 22  49  76 103]
 [ 28  64 100 136]
 [130 157 184 211]
 [172 208 244 280]]


In [111]:
tensor_product = C.reshape(2,2,4)
print(tensor_product)

[[[ 22  49  76 103]
  [ 28  64 100 136]]

 [[130 157 184 211]
  [172 208 244 280]]]


# 데이터 실습 - 판다스

텐서 형태로 데이터를 주세요 하면 csv파일 여러개로 줄 수도 있지만, 

행렬인데, 텐서를 행렬로 바꿨던 것처럼, 완전 붙여놨을 수도 있따는 것이다.

fashion-mnist_test 데이터는 이미지 데이터에 대한 것이다.

이미지가 10000 장이 있는데, 한 이미지에 여러 픽셀을 일렬로 펼쳐서 한 행으로 만들어버린 것이다.

In [112]:
import pandas as pd

df = pd.read_csv("./data/fashion-mnist_test.csv")

In [113]:
df

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0         0       0       0       0       0       0       0       0       9   
1         1       0       0       0       0       0       0       0       0   
2         2       0       0       0       0       0       0      14      53   
3         2       0       0       0       0       0       0       0       0   
4         3       0       0       0       0       0       0       0       0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995      0       0       0       0       0       0       0       0       0   
9996      6       0       0       0       0       0       0       0       0   
9997      8       0       0       0       0       0       0       0       0   
9998      8       0       1       3       0       0       0       0       0   
9999      1       0       0       0       0       0       0       0     140   

      pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          8  ...       103        87        56         0         0         0   
1          0  ...        34         0         0         0         0         0   
2         99  ...         0         0         0         0        63        53   
3          0  ...       137       126       140         0       133       224   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
9995       0  ...        32        23        14        20         0         0   
9996       0  ...         0         0         0         2        52        23   
9997       0  ...       175       172       172       182       199       222   
9998       0  ...         0         0         0         0         0         1   
9999     119  ...       111        95        75        44         1         0   

      pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0  
1            0         0         0         0  
2           31         0         0         0  
3          222        56         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
9995         1         0         0         0  
9996        28         0         0         0  
9997        42         0         1         0  
9998         0         0         0         0  
9999         0         0         0         0  

[10000 rows x 785 columns]

맨 위는 lable이다.

In [114]:
df.shape

(10000, 785)

In [115]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [116]:
X

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0          0       0       0       0       0       0       0       9       8   
1          0       0       0       0       0       0       0       0       0   
2          0       0       0       0       0       0      14      53      99   
3          0       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995       0       0       0       0       0       0       0       0       0   
9996       0       0       0       0       0       0       0       0       0   
9997       0       0       0       0       0       0       0       0       0   
9998       0       1       3       0       0       0       0       0       0   
9999       0       0       0       0       0       0       0     140     119   

      pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0           0  ...       103        87        56         0         0   
1           0  ...        34         0         0         0         0   
2          17  ...         0         0         0         0        63   
3         161  ...       137       126       140         0       133   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
9995       37  ...        32        23        14        20         0   
9996        0  ...         0         0         0         2        52   
9997        0  ...       175       172       172       182       199   
9998        0  ...         0         0         0         0         0   
9999      103  ...       111        95        75        44         1   

      pixel780  pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0         0  
1            0         0         0         0         0  
2           53        31         0         0         0  
3          224       222        56         0         0  
4            0         0         0         0         0  
...        ...       ...       ...       ...       ...  
9995         0         1         0         0         0  
9996        23        28         0         0         0  
9997       222        42         0         1         0  
9998         1         0         0         0         0  
9999         0         0         0         0         0  

[10000 rows x 784 columns]

In [117]:
y

0       0
1       1
2       2
3       2
4       3
       ..
9995    0
9996    6
9997    8
9998    8
9999    1
Name: label, Length: 10000, dtype: int64

In [118]:
X.shape

(10000, 784)

In [120]:
nx = int((X.shape[1])**0.5) # 정방형 이미지이기 때문에 루트를 씌웠다.

In [121]:
X = X.to_numpy()
X = X.astype('float32') / 255

In [122]:
import numpy as np
X = np.reshape(X, (X.shape[0], nx, nx, 1))