## 행렬식 구하기- 넘파이

In [1]:
import numpy as np

In [2]:
A = np.array([[3,2,0], [-1,-3,6], [2,3,-5]])

In [5]:
detA = np.linalg.det(A)

In [6]:
print(detA)

5.000000000000002


5.000000000000002 이건 부동소수점이라 신경안쓰셔도 됩니다.

## 역행렬 구하기

In [7]:
A = np.array([[3,2,0], [-1,-3,6], [2,3,-5]])

In [8]:
invA = np.linalg.inv(A)
print(A)
print('----')
print(invA)

[[ 3  2  0]
 [-1 -3  6]
 [ 2  3 -5]]
----
[[-0.6  2.   2.4]
 [ 1.4 -3.  -3.6]
 [ 0.6 -1.  -1.4]]


## 선형시스템

In [9]:
import pandas as pd

In [12]:
df = pd.read_csv('./data/netflix_price.csv')

In [13]:
df

Country  Total Library Size  No. of TV Shows  No. of Movies  \
0       Argentina                4760             3154           1606   
1         Austria                5640             3779           1861   
2         Bolivia                4991             3155           1836   
3        Bulgaria                6797             4819           1978   
4           Chile                4994             3156           1838   
..            ...                 ...              ...            ...   
60        Ireland                6486             4515           1971   
61    Switzerland                5506             3654           1852   
62      Australia                6114             4050           2064   
63        Denmark                4558             2978           1580   
64  United States                5818             3826           1992   

    Cost Per Month-Basic  Cost Per Month-Standard  Cost Per Month-Premium  
0                   3.74                     6.30                    9.26  
1                   9.03                    14.67                   20.32  
2                   7.99                    10.99                   13.99  
3                   9.03                    11.29                   13.54  
4                   7.07                     9.91                   12.74  
..                   ...                      ...                     ...  
60                  9.03                    14.67                   20.32  
61                 12.88                    20.46                   26.96  
62                  7.84                    12.12                   16.39  
63                 12.00                    15.04                   19.60  
64                  8.99                    13.99                   17.99  

[65 rows x 7 columns]

불러왔을 때는 항상 행렬의 크기를 보자. (이건 직사각행렬이구나, like this.)

In [14]:
X = df[['Cost Per Month-Basic','Cost Per Month-Standard', 'Cost Per Month-Premium']]
y = df['Total Library Size']

X는 행렬이고 y는 벡터

_본인이 뭘 하는지 항상 머릿속에 그림이 그려져 있어야 한다._

In [15]:
X

Cost Per Month-Basic  Cost Per Month-Standard  Cost Per Month-Premium
0                   3.74                     6.30                    9.26
1                   9.03                    14.67                   20.32
2                   7.99                    10.99                   13.99
3                   9.03                    11.29                   13.54
4                   7.07                     9.91                   12.74
..                   ...                      ...                     ...
60                  9.03                    14.67                   20.32
61                 12.88                    20.46                   26.96
62                  7.84                    12.12                   16.39
63                 12.00                    15.04                   19.60
64                  8.99                    13.99                   17.99

[65 rows x 3 columns]

y는 65by1일 텐데 그러기 위해서는 3by1 행렬을 곱해야한다.

3이 바로 피처의 개수. = w



w벡터의 추정치는 X전치행렬과 X 곱한것의 역행럴의 Xy

In [16]:
import numpy as np

In [17]:
Xt = np.transpose(X)

In [18]:
Xt

0      1      2      3      4     5      6      7   \
Cost Per Month-Basic     3.74   9.03   7.99   9.03   7.07  4.31   8.99   9.03   
Cost Per Month-Standard  6.30  14.67  10.99  11.29   9.91  6.86  12.99  11.29   
Cost Per Month-Premium   9.26  20.32  13.99  13.54  12.74  9.93  15.99  13.54   

                            8      9   ...     55     56     57     58    59  \
Cost Per Month-Basic      8.83   7.99  ...   9.03   9.03   7.91   8.36  4.61   
Cost Per Month-Standard  11.49  10.99  ...  11.29  14.67  13.20  10.66  7.11   
Cost Per Month-Premium   14.15  13.99  ...  13.54  20.32  18.48  12.96  9.96   

                            60     61     62     63     64  
Cost Per Month-Basic      9.03  12.88   7.84  12.00   8.99  
Cost Per Month-Standard  14.67  20.46  12.12  15.04  13.99  
Cost Per Month-Premium   20.32  26.96  16.39  19.60  17.99  

[3 rows x 65 columns]

X 트랜스포즈 * X

In [19]:
XtX = Xt.dot(X)

In [20]:
XtX

Cost Per Month-Basic  Cost Per Month-Standard  \
Cost Per Month-Basic                4792.3537                6841.1127   
Cost Per Month-Standard             6841.1127                9869.3585   
Cost Per Month-Premium              8904.0307               12892.8399   

                         Cost Per Month-Premium  
Cost Per Month-Basic                  8904.0307  
Cost Per Month-Standard              12892.8399  
Cost Per Month-Premium               16889.5490

### 역행렬로 바로 넘어가도 되지만 행렬식을 구해보자.

In [21]:
np.linalg.det(XtX)

12677160.526212221

In [22]:
XtX_inv = np.linalg.inv(XtX)

In [23]:
XtX_inv

array([[ 0.03657706, -0.0587723 ,  0.02558142],
       [-0.0587723 ,  0.13085974, -0.06890908],
       [ 0.02558142, -0.06890908,  0.03917547]])

뒤는 그냥 곱하면된다.

@ 가 행렬 곱을 의미한다.

In [24]:
w = XtX_inv@Xt@y

In [25]:
w

0    120.869221
1    850.639350
2   -394.814007
dtype: float64

머신러닝 하는 라이브러리에서도 결국 이런 전처리를 다 하고 한다는 것이다.

근데 그게 값이 이상하게 나올 때(무한대로 나온다던가 0으로 나올 때), 원리를 모르면 왜 이상한지 모르게 된다는 것!

넘파이가 좋지만 쓸모없는 값을 뱉을 때가 있다. (3*2행렬이 나와야 하는데 3*3으로 나오는 경우도 있는 것....) 세번째것은 무효값이다. 나중에 다시 설명할 것.)

In [29]:
w = np.matrix(w)
wt = np.transpose(w)

In [30]:
y = np.matrix(y)

In [31]:
X.dot(wt)

0
0   2155.101087
1   5547.707708
2   4790.823575
3   5349.385673
4   4254.450902
..          ...
60  5547.707708
61  8316.691040
62  4786.362040
63  6505.691939
64  5884.354818

[65 rows x 1 columns]

## 판다스 안쓰고 해보기

In [32]:
import csv

In [33]:
raw = []
with open("./data/netflix_price.csv", 'r', encoding = 'utf8') as f:
    rdr  = csv.reader(f)
    for line in rdr:
        raw.append(line)

In [34]:
raw

[['Country',
  'Total Library Size',
  'No. of TV Shows',
  'No. of Movies',
  'Cost Per Month-Basic',
  'Cost Per Month-Standard',
  'Cost Per Month-Premium'],
 ['Argentina', '4760', '3154', '1606', '3.74', '6.3', '9.26'],
 ['Austria', '5640', '3779', '1861', '9.03', '14.67', '20.32'],
 ['Bolivia', '4991', '3155', '1836', '7.99', '10.99', '13.99'],
 ['Bulgaria', '6797', '4819', '1978', '9.03', '11.29', '13.54'],
 ['Chile', '4994', '3156', '1838', '7.07', '9.91', '12.74'],
 ['Colombia', '4991', '3156', '1835', '4.31', '6.86', '9.93'],
 ['Costa Rica', '4988', '3152', '1836', '8.99', '12.99', '15.99'],
 ['Croatia', '2274', '1675', '599', '9.03', '11.29', '13.54'],
 ['Czechia', '7325', '5234', '2091', '8.83', '11.49', '14.15'],
 ['Ecuador', '4992', '3155', '1837', '7.99', '10.99', '13.99'],
 ['Estonia', '6456', '4486', '1970', '9.03', '11.29', '13.54'],
 ['France', '5445', '3604', '1841', '10.16', '15.24', '20.32'],
 ['Germany', '5668', '3814', '1854', '9.03', '14.67', '20.32'],
 ['Gibral

list 형태로 나오는데, 숫자가 문자형으로 되어있다. 이를 바꿔주는 작업부터 항상 시작하기.

In [35]:
n_row = len(raw)
n_col = len(raw[0])

In [38]:
data = []
for i in range(1,n_row): # 맨 위 첫 행이 이름로 되어있는 것 때문에
    row = []
    for j in range(1,n_col): # 맨 왼쪽 첫 컬럼이 나라 이름으로 되어있는 것 때문에
        val = float(raw[i][j])
        row.append(val)
    data.append(row)

In [39]:
data

[[4760.0, 3154.0, 1606.0, 3.74, 6.3, 9.26],
 [5640.0, 3779.0, 1861.0, 9.03, 14.67, 20.32],
 [4991.0, 3155.0, 1836.0, 7.99, 10.99, 13.99],
 [6797.0, 4819.0, 1978.0, 9.03, 11.29, 13.54],
 [4994.0, 3156.0, 1838.0, 7.07, 9.91, 12.74],
 [4991.0, 3156.0, 1835.0, 4.31, 6.86, 9.93],
 [4988.0, 3152.0, 1836.0, 8.99, 12.99, 15.99],
 [2274.0, 1675.0, 599.0, 9.03, 11.29, 13.54],
 [7325.0, 5234.0, 2091.0, 8.83, 11.49, 14.15],
 [4992.0, 3155.0, 1837.0, 7.99, 10.99, 13.99],
 [6456.0, 4486.0, 1970.0, 9.03, 11.29, 13.54],
 [5445.0, 3604.0, 1841.0, 10.16, 15.24, 20.32],
 [5668.0, 3814.0, 1854.0, 9.03, 14.67, 20.32],
 [6167.0, 4079.0, 2088.0, 9.03, 14.67, 20.32],
 [4772.0, 3344.0, 1428.0, 9.03, 12.42, 15.8],
 [4767.0, 3154.0, 1613.0, 7.99, 10.99, 13.99],
 [4989.0, 3154.0, 1835.0, 7.99, 10.99, 13.99],
 [4746.0, 2883.0, 1863.0, 8.08, 10.0, 11.93],
 [6387.0, 4426.0, 1961.0, 9.03, 14.67, 20.32],
 [5843.0, 3718.0, 2125.0, 2.64, 6.61, 8.6],
 [5713.0, 3650.0, 2063.0, 10.56, 15.05, 19.54],
 [5183.0, 3545.0, 1638.

첫 행을 날려서 65가 되는 것. 첫 행이 제목이어서. (익숙해지기)

### data로

In [40]:
X = [] 
for i in range(0, n_row-1):
    row = []
    for j in range(3,6):
        row.append(data[i][j])
    X.append(row)

In [41]:
X

[[3.74, 6.3, 9.26],
 [9.03, 14.67, 20.32],
 [7.99, 10.99, 13.99],
 [9.03, 11.29, 13.54],
 [7.07, 9.91, 12.74],
 [4.31, 6.86, 9.93],
 [8.99, 12.99, 15.99],
 [9.03, 11.29, 13.54],
 [8.83, 11.49, 14.15],
 [7.99, 10.99, 13.99],
 [9.03, 11.29, 13.54],
 [10.16, 15.24, 20.32],
 [9.03, 14.67, 20.32],
 [9.03, 14.67, 20.32],
 [9.03, 12.42, 15.8],
 [7.99, 10.99, 13.99],
 [7.99, 10.99, 13.99],
 [8.08, 10.0, 11.93],
 [9.03, 14.67, 20.32],
 [2.64, 6.61, 8.6],
 [10.56, 15.05, 19.54],
 [9.03, 14.67, 20.32],
 [8.73, 13.13, 17.45],
 [12.88, 20.46, 26.96],
 [8.29, 10.65, 13.02],
 [6.62, 10.43, 14.24],
 [9.03, 11.29, 13.54],
 [9.03, 13.54, 18.06],
 [9.94, 12.17, 17.75],
 [8.29, 11.49, 14.69],
 [6.11, 8.56, 11.01],
 [7.35, 9.14, 10.93],
 [7.13, 10.58, 14.76],
 [9.03, 11.29, 13.54],
 [8.13, 10.84, 13.56],
 [9.03, 14.67, 20.32],
 [9.03, 11.29, 13.54],
 [6.26, 10.05, 12.58],
 [8.07, 11.47, 14.45],
 [9.74, 11.9, 14.07],
 [8.34, 10.43, 12.52],
 [1.97, 3.0, 4.02],
 [5.64, 8.46, 11.29],
 [8.99, 12.99, 15.99],
 [7

하나하나 리스트 형태로 들어가 있다.

In [42]:
y = []
for i in range(0, n_row-1):
    y.append(data[i][0])
    # 한 행에 대해서만 값을 뽑으면 되기 때문에

In [43]:
y

[4760.0,
 5640.0,
 4991.0,
 6797.0,
 4994.0,
 4991.0,
 4988.0,
 2274.0,
 7325.0,
 4992.0,
 6456.0,
 5445.0,
 5668.0,
 6167.0,
 4772.0,
 4767.0,
 4989.0,
 4746.0,
 6387.0,
 5843.0,
 5713.0,
 5183.0,
 5475.0,
 3048.0,
 5952.0,
 4993.0,
 3937.0,
 5804.0,
 4528.0,
 4797.0,
 4986.0,
 6362.0,
 5109.0,
 5303.0,
 5711.0,
 2310.0,
 7035.0,
 5736.0,
 5195.0,
 5105.0,
 4948.0,
 4639.0,
 5336.0,
 4989.0,
 4797.0,
 4990.0,
 6303.0,
 4045.0,
 6450.0,
 6084.0,
 6884.0,
 5047.0,
 5376.0,
 4361.0,
 6239.0,
 6462.0,
 5229.0,
 6643.0,
 3887.0,
 4972.0,
 6486.0,
 5506.0,
 6114.0,
 4558.0,
 5818.0]

### 선형방정식의 해 구하기

In [44]:
Xt = np.transpose(X)

In [45]:
Xt_inv = np.linalg.inv(Xt@X)

In [46]:
Xt_inv

array([[ 0.03657706, -0.0587723 ,  0.02558142],
       [-0.0587723 ,  0.13085974, -0.06890908],
       [ 0.02558142, -0.06890908,  0.03917547]])

In [47]:
w = Xt_inv@Xt@y

In [48]:
w

array([ 120.86922078,  850.63935047, -394.81400721])

In [49]:
wt = np.transpose(w)

In [50]:
X@wt

array([2155.10108686, 5547.70770842, 4790.82357474, 5349.38567274,
       4254.45090214, 2435.82919414, 5823.34348203, 5349.38567274,
       5254.50315428, 4790.82357474, 5349.38567274, 6169.15435766,
       5547.70770842, 5547.70770842, 5418.32848247, 4790.82357474,
       4790.82357474, 4772.88570251, 5547.70770842, 2546.42038742,
       6363.83549501, 5547.70770842, 5334.57854316, 8316.69103973,
       4920.83654881, 4050.17120422, 5349.38567274, 5478.76489869,
       4545.77232169, 4976.03421116, 3673.08155954, 4347.91533715,
       4034.10712563, 5349.38567274, 4849.91938618, 5547.70770842,
       5349.38567274, 4338.80658353, 5027.18555731, 5744.84139945,
       4937.14635635, 1202.87810734, 3420.66116871, 5823.34348203,
       4790.82357474, 6169.15435766, 5685.70271288, 5478.76489869,
       5349.38567274, 5034.01092202, 4593.25127086, 5478.76489869,
       5478.76489869, 5618.71734102, 5119.11009799, 5349.38567274,
       5547.70770842, 4888.35210923, 4961.4926282 , 2672.90537