# LU 분해

## 넘파이 실습

In [1]:
import numpy as np
from scipy.linalg import lu # lu분해는 scipy 안에 있음

In [2]:
A = np.array([[2,-2,-2],[0,-2,2],[-1,5,2]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [5]:
L

array([[ 1. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ],
       [ 0. , -0.5,  1. ]])

In [6]:
U

array([[ 2. , -2. , -2. ],
       [ 0. ,  4. ,  1. ],
       [ 0. ,  0. ,  2.5]])

In [7]:
# A = LU 확인

L@U

array([[ 2., -2., -2.],
       [-1.,  5.,  2.],
       [ 0., -2.,  2.]])

L@U가 P에 의해서 행의 순서가 바뀐 것이 반영되서 나온다.

# 텐서 실습

### 각 원소에 접근하기

In [10]:
# 벡터 : 리스트 한 겹
# 각 원소에 접근할 때 대괄호도 하나
x = [1, 2]

In [11]:
x[0]

1

In [12]:
x[1]

2

In [8]:
# 행렬 : 리스트 두 겹
# 각 원소에 접근할 때 대괄호가 둘
A = [[1, 2], [3, 4]]

In [13]:
A[0][0]

1

In [14]:
A[0][1]

2

In [15]:
A[1][0]

3

In [16]:
A[1][1]

4

### 텐서 만들기

In [19]:
# 텐서 : 리스트가 세 겹
T = [[[1, 2],[3, 4]], [[5, 6], [7, 8]]]

채널 번수가 맨 앞으로 온다는 것을 기억해야 한다.

In [20]:
T[0][0][0]

1

In [21]:
T[0][0][1]

2

In [22]:
T[0][1][0]

3

In [23]:
T[0][1][1]

4

In [24]:
T[1][0][0]

5

In [25]:
T[1][0][1]

6

In [26]:
T[1][1][0]

7

In [27]:
T[1][1][1]

8

## 텐서의 노름 구하기

In [28]:
A = [ [[1,0,1,0], [2,1,0,1], [3,4,0,2]],
      [[3,1,2,0], [1,0,4,2], [0,1,0,2]]  ]

In [29]:
print(A)

[[[1, 0, 1, 0], [2, 1, 0, 1], [3, 4, 0, 2]], [[3, 1, 2, 0], [1, 0, 4, 2], [0, 1, 0, 2]]]


In [32]:
n = len(A[0])    # 열 벡터의 개수
p = len(A[0][0]) # 행 벡터의 개수
q = len(A)       # 행렬이 몇 개

In [33]:
print(n, p, q)

3 4 2


In [35]:
norm = 0
for i in range(0, n):
    for j in range(0, p):
        for k in range(0, q):
            norm += A[k][i][j]**2

norm = norm**0.5

In [37]:
print(norm)

8.774964387392123


## 텐서의 내적 구하기

채널번호가 가장 앞에 오는거 까먹지 말기

### 파이썬으로 하기

In [38]:
A = [ [[1,0,1,0], [2,1,0,1], [3,4,0,2]],
      [[3,1,2,0], [1,0,4,2], [0,1,0,2]]  ]
B = [ [[2,1,3,1], [0,2,1,3], [1,0,1,1]],
      [[1,2,3,1], [3,1,0,3], [0,2,3,1]]  ]

In [39]:
n = len(A[0])
p = len(A[0][0])
q = len(A)

In [41]:
inner_product = 0
for i in range(0, n):
    for j in range(0, p):
        for k in range(0, q):
            inner_product += A[k][i][j] * B[k][i][j]

In [42]:
print(inner_product)

39


### 넘파이로 하기

In [43]:
import numpy as np

# 넣는 것 array로 안하고 리스트로 바로 넣어도 값은 같게 나올 수 있다.

In [44]:
A = np.array([ [[1,0,1,0], [2,1,0,1], [3,4,0,2]],
               [[3,1,2,0], [1,0,4,2], [0,1,0,2]]  ])
B = np.array([ [[2,1,3,1], [0,2,1,3], [1,0,1,1]],
               [[1,2,3,1], [3,1,0,3], [0,2,3,1]]  ])

In [45]:
C = np.multiply(A, B)

In [46]:
print(C)

[[[2 0 3 0]
  [0 2 0 3]
  [3 0 0 2]]

 [[3 2 6 0]
  [3 0 0 6]
  [0 2 0 2]]]


In [48]:
inner_product = np.sum(C)
print(inner_product)

39
