<a href="https://colab.research.google.com/github/Angela-Park-JE/TIL_ver1/blob/main/Numpy/Wanted_pre_231101_numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy의 활용

https://www.youtube.com/watch?v=Ohein9rZ4fk&list=PLRx0vPvlEmdBx9X5xSgcEk4CEbzEiws8C&index=6&pp=iAQB


넘파이의 다양한 함수를 알아보도록 하자.

## Numpy 단일 객체 저장 및 불러오기

실행하면 하나의 파일이 생성된다.

In [2]:
# 저장
array = np.arange(0, 10)
np.save('saved.npy', array)

In [3]:
# 불러오기
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


## Numpy 복수 객체 저장 및 불러오기

save'z' 와 각 객체를 이름을 지정하여 저장한다.  
확장자 명도 자신이 저장하고 싶은 형태로 저장할 수 있다.

In [4]:
# 저장
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', arr1 = array1, arr2 = array2)

In [5]:
# 불러오기
data = np.load('saved.npz')
result1 = data['arr1']
result2 = data['arr2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [6]:
# 불러온 것 자체는 객체로만 보이도록 되어있다.
print(data)

## Numpy 원소의 정렬

기본은 오름차순이다.

In [7]:
array = np.array([5, 9, 3, 10, 1])
print(array)

# 원소 오름차순 정렬
array.sort()
print(array)

# 원소 내림차순 정렬
# 정렬된 이후에 인덱싱 기법을 활용하여 거꾸로 출력하도록 한다.
print(array[::-1])

[ 5  9  3 10  1]
[ 1  3  5  9 10]
[10  9  5  3  1]


### 열 기준 원소 정렬

In [8]:
# 각 열을 기준으로 정렬 (오름차순)
array = np.array([[5, 9, 3, 10, 1], [8, 2, 6, 4, 7]])
print(array)
array.sort(axis = 0)
print(array)

[[ 5  9  3 10  1]
 [ 8  2  6  4  7]]
[[ 5  2  3  4  1]
 [ 8  9  6 10  7]]


## 데이터 생성 함수

- `np.linspace(start, end, num)` : num 개수 만큼 균일한 간격으로 데이터 생성하기

In [9]:
# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


- `np.random.randint(start, end, (n, p))` : n행 p열의 구간 속 랜덤 정수로 데이터 생성한다. (난수의 재연)

    이때 `np.random.seed()`를 정하고 시작하면 같은 값만 출력되게 된다.

In [10]:
# 난수의 재연(실행 결과마다 동일)
np.random.seed(9)
print(np.random.randint(0, 10, (2, 3)))

[[5 6 8]
 [6 1 6]]


## Numpy 배열 객체 복사

Numpy에서는 array2 = array1 으로 array1을 담긴 했지만 동일한 주소를 가리키게 되기 때문에 array2의 값을 바꾸면 array1의 값도 바뀌게 된다. (변수명 담듯이 복사하면 deep copy가 됨.)

In [11]:
# Numpy 배열 객체가 올바르게 복사되지 않았을 때
arr1 = np.arange(0, 10)
arr2 = arr1
arr2[0] = 99
print(arr1)

[99  1  2  3  4  5  6  7  8  9]


예방하기 위해서 복사(`arr.copy()`)하는 작업이 필요하다.

In [12]:
# Numpy 배열 객체의 복사
arr1 = np.arange(0, 10)
arr2 = arr1.copy()
arr2[0] = 99
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]


## 중복된 원소 제거

np.unique(array)

In [13]:
# 중복되는 원소 제거
arr = np.array([1,1,2,2,2,3,3,4,4,5])
print(np.unique(arr))

[1 2 3 4 5]
