<a href="https://colab.research.google.com/github/Angela-Park-JE/TIL_ver1/blob/main/Numpy/Wanted_pre_231030_numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### list를 Numpy로 바꾸기

- `np.array(list)`

In [2]:
list_data = [1, 2, 3]
print(list_data)

[1, 2, 3]


In [3]:
array = np.array(list_data)
print(array)

[1 2 3]


### Numpy 데이터의 함수

- `arr.size`
- `arr.dtype`
- `arr[index]`

In [4]:
# 배열의 크기
array.size

3

In [5]:
# 배열 원소의 타입
array.dtype

dtype('int64')

In [6]:
# 특정 위치 원소 - 인덱스로 접근
array[2]

3

## Numpy 배열 초기화하기

### 배열 만들기 : `np.arange(int)`

In [7]:
# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


### 0으로 채운 배열 만들기: `np.zeros((p, q), dtype = )`

In [8]:
# 특정 데이터를 만들되, 0으로 초기화 되어있는 배열 만들기
array2 = np.zeros((4, 4), dtype = float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 1으로 채운 배열 만들기: `np.ones((p, q), dtype = )`

In [9]:
# 특정 데이터를 만들되, 1로 초기화 되어있는 배열 만들기
array3 = np.ones((3, 3), dtype = str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


### 특정 범위 내의 수로 배열 만들기:

In [10]:
# 0부터 9까지 랜덤하게 초기화 된 배열을 만들기
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

[[6 3 9]
 [5 7 9]
 [6 9 8]]


### 특정 분포를 따르는 무작위 데이터 만들기

In [11]:
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[[ 0.06823972 -1.55944318 -2.2776293 ]
 [ 1.3942815  -0.04252446  0.24484509]
 [ 0.4220193  -1.21712012 -1.07148227]]


## 배열 형태 바꾸기

`array.reshape((p, q))`

_과정 순서상 마지막쪽에 있긴함._

In [12]:
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))

print(array2.shape)

(2, 2)


## 배열 합치기

 `np.concatenate([array1, array2...])`

 기본적으로 열(가로)방향으로 합쳐지게 된다.

In [13]:
# 가로축 합치기

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


배열 세로 축으로 합치기:
`np.concatenate([array1, array2], axis = 0)`

In [14]:
array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

print(array1)
print(array2)

array3 = np.concatenate([array1, array2], axis = 0)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


자율 학습 : 기본값 알아두기위한 몸부림

In [15]:
# 만약 저 axis=0으로 했던 예제에서 array에 축 지정을 안했다면?
# 벡터와 행렬의 concat

# array1 = np.arange(4).reshape(1, 4)
# array2 = np.arange(8).reshape(2, 4)

# print(array1)
# print(array2)

array4 = np.concatenate([array1, array2])
print(array4)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


### 직접 예시 만들어보기

1. `np.zeros`나 `np.ones`는 기본적으로 벡터를 만든다.

In [16]:
# reshape로 지정하는 것의 차이
# shape가 ('1, 5'가 아니라 '5,'로 나옴)

s = np.zeros(5)
ss = np.zeros(5).reshape(1, 5)

print(s.shape)
print(ss.shape)

(5,)
(1, 5)


2. 벡터간에 concatenate는 해당 방향으로 붙게 되어있다.

In [17]:
# 벡터
v1 = np.zeros(5)
v2 = np.ones(5)
v3 = np.array([2, 2]).reshape(2, 1) # 열벡터

In [18]:
# 기본적으로 벡터는 같은 방향으로 붙이게 되어있다.
print(np.concatenate([v1, v1, v2, v2]))
print(np.concatenate([v3, v3]))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[2]
 [2]
 [2]
 [2]]


3. 벡터를 행렬의 형태(1XQ or PX1)로 만든 경우는 행 방향으로 붙는다.

In [19]:
# 그러나 .reshape() 로 행을 지정하여 하나의 행렬로 주어졌을 때는 다르다

v1 = np.zeros(5).reshape(1, 5)
v2 = np.ones(5).reshape(1, 5)
v3 = np.array([2, 2]).reshape(2, 1) # 열벡터

print(np.concatenate([v1, v1, v2, v2])) # 행백터가 행방향으로 붙음
print(np.concatenate([v3, v3])) # 열벡터도 행방향으로 붙는다.

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2]
 [2]
 [2]
 [2]]


4. 벡터간의 concatenate는 열방향으로 붙기 때문에 `axis = 0`을 적는다 하더라도 기본적으로 열방향으로 이어붙여진다.  
`axis = 1`은 먹지 않는다.

In [20]:
# 행렬을 만들 때, 이런식으로 만들면 벡터와 벡터를 합친 것으로, 열 기준으로 합쳐진다. (행렬이 안됨)
m1 = np.concatenate([np.array(list([3]*5)), np.array(list([4]*5))], axis = 0)
print(m1)

[3 3 3 3 3 4 4 4 4 4]


In [21]:
# 행렬로 만들고자 axis = 1은 먹지 않는다.
# m2 = np.concatenate([np.array(list([5]*5)), np.array(list([6]*5))], axis = 1)
# print(m2)

5. 벡터로 행렬을 만들고자 한다면 벡터를 행렬로 만들거나 (1번), `reshape()`로 행과 열을 지정해주어 재배열 해야한다.

In [22]:
# 벡터들만으로 행렬로 만들고자한다면 reshape를 이용할 수 밖에 없다.
m1 = np.concatenate([np.array(list([3]*5)), np.array(list([4]*5))]).reshape(2, 5)
m2 = np.concatenate([np.array(list([5]*5)), np.array(list([6]*5))]).reshape(2, 5)
print(m1, '\n', m2)

[[3 3 3 3 3]
 [4 4 4 4 4]] 
 [[5 5 5 5 5]
 [6 6 6 6 6]]


6. 행벡터 행렬끼리는 행 방향으로 붙는다.

In [23]:
# 아마 벡터는 기본적으로 열방향으로 붙여주지만, 매트릭스는 행(세로)축으로 합치는 것 같다.

# 벡터 - 이지만 reshape을 붙여주지 않으면 행으로 인식하지 않는다
v1 = np.zeros(5).reshape(1, 5)
v2 = np.ones(5).reshape(1, 5)
v3 = np.array([2, 2]).reshape(2, 1) # v3 = np.random.randint(2, 3, (2, 1))

m1 = np.concatenate([np.array(list([3]*5)), np.array(list([4]*5))]).reshape(2, 5)
m2 = np.concatenate([np.array(list([5]*5)), np.array(list([6]*5))]).reshape(2, 5)

In [24]:
# 행벡터와 행벡터 간
print(np.concatenate([v1, v2]))

# 행벡터와 행벡터를 여러개로 넣었을 때
print(np.concatenate([v1, v2, v1, v2]))

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


7. 행벡터 행렬도 방향을 열로 붙이도록 `axis=1`을 지정하면 열방향으로 붙는다.

In [25]:
# 행벡터와 행벡터 간 방향을 지정했을 때
print(np.concatenate([v1, v2], axis = 1))

# 행벡터와 행벡터를 여러개로 방향을 지정했을 때
print(np.concatenate([v1, v2, v1, v2], axis = 1))

[[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]


8. 열벡터의 행 갯수와 행렬의 행의 개수가 같아도 붙여지지 않는다.  
열의 개수가 같은 행벡터 행렬과 행렬은 행 방향으로 붙는다.

In [26]:
# 벡터와 행렬 간 (행 개수가 같을 때)
# print(np.concatenate([v3, m1])) # 오류가 나며 실행 안됨

# 벡터와 행렬 간 (열 개수가 같을 때)
print(np.concatenate([v1, m1]))

[[0. 0. 0. 0. 0.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


9. 열의 개수가 같다면 행렬끼리는 자동적으로 행방향으로 붙는다. (가장 기본 형태)

In [27]:
# 행, 열의 개수가 같을 때
# 행렬과 행렬 간 # 자동적으로 행방향으로 붙는다.
print(np.concatenate([m1, m2]))

# 행렬과 행렬을 여러개로 넣었을 때
print(np.concatenate([m1, m2, m1, m2]))

[[3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [6 6 6 6 6]]
[[3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [6 6 6 6 6]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [6 6 6 6 6]]


10. 행의 개수가 같고 열의 개수가 다른 경우에는 열 방향으로 붙이라고 지정해주어야 오류 없이 concat이 가능하다.

In [28]:
# 행의 개수가 같은 행렬은 어떻게 될까?
m3 = np.random.randint(0, 10, (3, 3))
m4 = np.random.randint(10, 20, (3, 5))

# 그냥은 오류가 나고, 열방향으로 붙여달라고 해야 작동한다.
# 행렬간 기본은 행 방향으로 붙는 것이 맞다.
# print(np.concatenate([m3, m4]))
print(np.concatenate([m3, m4], axis = 1))
print(np.concatenate([m3, m4], axis = 1).shape)

[[ 3  6  5 16 14 17 10 19]
 [ 7  2  4 16 15 16 12 19]
 [ 4  8  8 17 13 11 12 13]]
(3, 8)


## 배열 나누기

2차원 데이터를 나눌 때 split을 이용할 수 있다.
`np.split(array, [기준], axis = 기준방향)`

In [29]:
# 8개의 값, 2행 4열
array = np.arange(8).reshape(2, 4)

# [2]'열'을 중심으로 값을 나눈다
left, right = np.split(array, [2], axis = 1)

print(left.shape)
print(right.shape)

print(array)
print(left)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]]


In [30]:
# 만약 행 중심으로 나눈다면?
upper, lower = np.split(array, [1], axis = 0)

print(upper.shape)
print(lower.shape)

print(array)
print(upper)

(1, 4)
(1, 4)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]]
